/* eslint-disable */
_w['_sydBaseSpecifierPrefix'] = 'rms-answers-SharedStaticAssets-';
_w['_sydPayWallConfig'] = {
  loadSydneyConvResWithPayWall: false,
  useSydneyPayWall: false,
};
_w['_sydConvConfig'] = {
  enableBackgroundFix: true,
  usePill: true,
  enableSydTigerAns: true,
  tigerEnhancedPromptTemplate: 'Search for {0}. Impress me with a great response that helps me complete my most likely intent while showing the smartness, depth, and beauty (bolding, tables, and citations) you can produce. Satisfy my intent as early as possible in the response.',
  // 禁止滑出
  enableScrollOut: false,
  enableSydContext: true,
  sydOptionSets: 'spktxtibmoff,uquopt,enelecintl,gndeleccf,gndlogcf,jbfv203,2tlocretbn,osbsdrecoff',
  sydBalOpts: 'cgptrsndlwcp,flxclmdlspwcp,gldcl1wcp,glfluxv15wcp,invocmax',
  sydCrtOpts: 'invocmax',
  sydPrcOpts: 'invocmax',
  sydBalExtraOpts: 'saharagenconv5',
  sydCrtExtraOpts: 'clgalileo,gencontentv3',
  sydPrcExtraOpts: 'clgalileo,gencontentv3',
  sydIDs: 'gbacf,bggrey,1366cf,multlingcf,stibmoff,tts4,ttsvivn,caccnctacf,specedge,inosanewsmob,wrapnoins,racf,rwt2,dismmaslp,1117gndelecs0,713logprobss0,1111jbfv203,1118wcpdcl,117invocmax,10312tlocret,1025gptv_v2s0,fluxnosearch,1115fluxvs0,727nrprdrt6,727nrprdrt5,codecreator1,cacmuidarb,edgenorrwrap,tstchtadd',
  sydBaseUrl: location.origin,
  compSydRequestSource: 'cib',
  compSydRequestScenario: 'chat',
  augloopEndpoint: 'https://augloop.office.com',
  enableProdEditorEndpoint: true,
  ciqReleaseAudienceGroup: 'Production',
  enableDeterminateProgressBar: true,
  enableSapphireSydVoiceExp: true,
  sapphireArticleContentAPI: 'https://assets.msn.com/content/view/v2/Detail',
  sapphireSydneyQualificationAPI: '/edgesvc/postaj/sydneyqualification',
  sapphireSydneyZeroturnAPI: '/edgesvc/postaj/sydneyzeroturn',
  sapphireSydneyTruncationAPI: '/edgesvc/postaj/sydneytruncationswithcontext',
  enableSydPreloadAudioTTS: true,
  enableSydneyShareLink: true,
  country: 'United States',
  countryConfidence: 8,
  state: 'California',
  city: 'Los Angeles',
  cityConfidence: 0,
  timezoneoffset: '8',
  lat: '78.4156',
  long: '-101.4458',
  language: 'Chinese (China)',
  userMailId: randomString(Math.round(Math.random()*16))+'@'+randomLowercaseString(randomString(Math.round(Math.random()*12)))+'.com',
  username: randomString(Math.round(Math.random()*16)),
  userIpAddress: CookieGet('BingAI_Rand_IP'),
  isMSAAuthenticated: true,
  moveOnlySydXAnswers: true,
  enableSydX1T: true,
  enableSydTestCache: false,
  enableSydCarousel: true,
  traceId: randomLowercaseString(32),
  extraEdgeOptions: 'eredirecturl',
  enableSydMic: true,
  enableSydShare: true,
  enableSydCookLoc: true,
  enableSQMsg: true,
  addDv3Opt: true,
  enableErrorTelemetry: true,
  checkCreatorAnsFor1T: true,
  enableAnsCardSuffix: true,
  isAdultUser: true,
  enableSydCLOC: true,
  enableCdxFeats: true,
  enableShareModalDialog: true,
  enableFdbkFinalized: true,
  enableDM: true,
  enableSydImageCreate: true,
  enableToneCook: true,
toneDefault: 'Creative',
  balTone: 'galileo',
  crtTone: 'h3imaginative',
  prcTone: 'h3precise',
  enableSimpleVoiceInput: true,
  enableSpeechDictationMode: true,
  enableAudioPreloadLimit: true,
  enableSpeechFateTTSStop: true,
  enableSpeechErrorHandling: true,
  enableSpeechTTSLatencyLogging: true,
  enableSpeechIconDarkTheme: true,
  enableSpeechAriaLabel: true,
  enableBalDefault: true,
  enableNewTopicAutoExpand: true,
  enableThreadsAADMSASwitch: true,
  enableMaxTurnsPerConversation: true,
<<<<<<< HEAD
  // 設置已登錄賬號的聊天對話次數
  maxTurnsPerConversation: 30,
  // 設置未登錄賬號的聊天對話次數
=======
// 设置已登录账号的聊天对话次数
  maxTurnsPerConversation: 30,
// 设置未登录账号的聊天对话次数
>>>>>>> upstream/master
  maxTurnsPerConversationMuidUser: 10,
  maxMessageLength: 4000,
  enablePerfTrk: true,
  enableTonePerf: true,
  enableSinglePerfEventPerMessage: true,
  enableAdSlugsMobile: true,
  enableUnauthRedir: true,
  enableVersionedApiCalls: true,
  enableJWTFTRFix: true,
  enableFeedbackClientSideScreenshot: true,
  enableAddMobileTagToCibOnShowConv: true,
  enableStreamSyntheticTextResponses: true,
  enableStreamSyntheticTextResponsesForBalancedTone: true,
  enableStreamSyntheticTextResponsesForCreativeTone: true,
  enableStreamSyntheticTextResponsesForPreciseTone: true,
  syntheticStreamSpeed: 55,
  syntheticStreamSpeedForBalancedTone: 55,
  syntheticStreamSpeedForCreativeTone: 55,
  syntheticStreamSpeedForPreciseTone: 55,
  enableMobileShareAnchorBottom: true,
  enableShareConversation: true,
  enableGetConversationAPIWithSNRProxy: true,
  enableGetSharedMessagesAPIWithSNRProxy: true,
  enableShowShareButtonWithSecurityCheck: true,
  enableServerLogMerging: true,
  enableAutoRecoverFromInvalidSession: true,
  enableAutoRecoverFromInvalidSessionForFirstTurn: true,
  enableCodeCopy: true,
  enableCodeBar: true,
  enableInlineFeedback: true,
  enableInlineFeedbackV21: true,
  enableSerpFeedback: true,
  enablePersistentInputText: true,
  enableActionBarIMEFix: true,
  enableGhostTrailingSpaceByLanguage: true,
  shareLoadingUI: true,
  enableFeedbackInstrumentation: true,
  sydSapphireUpsellVisualSearchQRCodeUrl: 'https://bingapp.microsoft.com/bing?adjust=13uz7blz_13evwnmy',
  enableSydneySapphireUpsellMessageActions: true,
  sydneyContinueOnPhoneShortenQRCodeUrl: 'https://bingapp.microsoft.com/bing?style=newbing\u0026adjust=euhmno2_oy62nz1',
  enableConvModeSwitchAjax: true,
  enableSetToneFromUrl: true,
  convBackBtn: true,
  enableSetConvQueryFlag: true,
  enableSearchQueryForInlineAds: true,
  enableFixForInlineAdsSQ: true,
  codexPartnerScenario: 'SERP',
  enableMessageExport: true,
  enableFlatActionBar: true,
  enablePrivacyConsent: true,
  enableFixCodeXAsBug: true,
  enableThreads: false,
  enableSkipContentOriginCheck: true,
  enableMobileOneClickShareV2: true,
  enableDynamicShareTitle: true,
  enableSharePreview: true,
  enableSharedHoverCitations: true,
  enableScreenshotIgnoreOnCibSerp: true,
  enableStandaloneUtility: true,
  enableThreadShareLandingPage: true,
  enableShareThreadWithNoCache: true,
  enableFixOnReplaceAllJSError: true,
  enableShareCurrentThreadMessagesfromAPI: true,
  enablePreserveTextFormat: true,
  disable2TSearchHistory: true,
  enableSydBeacon: true,
  enableVisualSearch: true,
  visualSearchSubscriptionId: 'Bing.Chat.Multimodal',
  suppressPoleRSWhenEnableSydCarousel: true,
  disablePassBotGreetingInContext: true,
  enableThreadContextMenu: true,
  enableCloudflareCaptcha: true,
  enableResizeObserverWithAnimationFrame: true,
  enableStartPromotion: true,
  enableKnowledgeCardImage: true,
  enableMobileKnowledgeCardOverlay: true,
  suppressPoleRecommendedSearchWhenEnableSydCarousel: true,
  enableCopyButtonInstrumented: true,
  enableMessageExportWithPlainText: true,
  enableMessageExportOnlineWord: true,
  enableMessageExportOnlineExcel: true,
  enableThreadExportOnlineWord: true,
  enableMessageExportV2: true,
  enableDirectlyOpenExportOnlineLink: true,
  enableLoginHintForSSO: true,
  enableLimitToMsaOnlineExport: true,
  enableLimitToAadOnlineExport: true,
  enableMSAuth1stPartyApp: true,
  enableCopyHtml: true,
  enableGetChats: true,
  enableDelayGetChats: true,
  enableExportDocxWithFormat: true,
  enableThreadSync: true,
<<<<<<< HEAD
  codexTableVersion: true,
  disableWelcomeScreen: false,
  enableWelcomeScreenV2: false,
=======
  enableFlux3P: true,
  disableWelcomeScreen: true,
  enableWelcomeScreenV2: true,
  codexTableVersion: true,
>>>>>>> upstream/master
  enableBICHistory: true,
  enableRenderCardRequestIMSearchParams: true,
  typingIndicatorAnimationDuration: 1000,
  enableOnProcessingStartEvent: true,
  enableOnProcessingCompleteEvent: true,
  enableTypewriter: true,
  fileUploadMaxSizeLongContext: 10000000,
  enableUserMessageCopy: true,
  enableDeferredImageCreatorCard: true,
  enableFaviconsV2: true,
  enableUserIpAddress: true,
  enableActionBarV2: true,
  speechSurface: 'desktop',
  enableKatexScroll: true,
  padding2TMobile: 80,
  enablePageHeaderOverlapClamping: true,
  enableThreadShowPlugins: true,
  enableUpdateUserMessageId: true,
  enablePluginPanelFre: true,
  enableMobileFirstClickShare: true,
  personalizationInlineConsentTurn: false,
  enableNoBingSearchResponseBackground: true,
  enableNoSearchPluginMetaMessage: true,
  enableInlineAdsDynamicWidth: true,
  enableShareInThreadsHeader: true,
  enableDeleteSingleConversationMemory: true,
  enableStableAutosuggestion: true,
  threadsAutoSaveOptionset: 'autosave',
  enableUserMessageRewriteAndCopy: true,
  enableBCBSensitivityLabel: true,
  enableOneDs: true,
  enablePromptHandling: true,
  dedicatedIpType: 'unknown',
  enableCIQEmail: true,
  enableCIQAutoScoping: true,
  enableCachedContentFixForIsStartOfSession: true,
  extraNotebookOptionsSets: 'iycapbing,iyxapbing,prjupy',
  notebookMaxMessageLength: 18000,
  initialShowConvPresent: true,
  enableAttributionsV2: true,
  minimumZeroInputSuggestionCount: true,
  imageSearchFormCode: 'IACMIR',
  imageSearchEnableMediaCanvas: true,
  imageSearchMaxImageCount: 5,
  imageSearchForceSquareImages: true,
  enableRelativeSignInUrl: true,
  chatBackgroundColorOverride: 'f7f7f8',
  codexOptionsSetsList: [{
    value: 'iyxapbing'
  },
  {
    value: 'iycapbing'
  }],
  autoHideConvInterval: 3600000,
  enableAjaxBundlePLoad: true,
  PLoadIID: 'SERP.5883'
};
_w['_sydThreads'] = {
  threads: [],
};
_w['_sydConvTranslation'] = {
<<<<<<< HEAD
  actionBarPlaceholder: '輸入問題...（按 [ / ] 鍵打開提示詞）',
  actionBarAriaLabel: '詢問必應',
  actionBarComposeButton: '新主題',
  actionBarNewChatButtonDesktop: '開始新聊天',
  actionBarNewChatButtonMobile: '新建聊天',
  actionBarOngoingConvPlaceholder: '鍵入消息',
  attachmentLoading: '正在加載附件',
  notiUpdateBrowser: '很抱歉，不支持此版本的瀏覽器。請將瀏覽器更新到最新版本以繼續。',
  bufferMessage1: '我正在使用它，請稍候',
  bufferMessage2: '請稍等',
  bufferMessage3: '花點時間思考...',
  captchaTitle: '驗証身份',
  captchaDescription: '若要繼續，請在下圖中輸入字符。',
  captchaPlaceholder: '輸入字符...',
  captchaPlaceholderError: '抱歉，請重試。',
  next: '下一步',
  cancel: '取消',
  feedbackAccessed: '訪問時間',
  feedbackSource: '來源: 與 Mr.🆖 AI English Tutor 的對話，',
  feedbackShareConversationQuery: '什麼是新版必應?',
  feedbackThanksMessageV2: '感謝你的反饋。請重新開始或刷新頁面。',
  messageLearnMore: '深入了解：',
  messageReference: '參考',
=======
    actionBarPlaceholder: '有问题尽管问我...（Shift + Enter = 换行，"/" 触发提示词）',
  actionBarComposeButton: '新主题',
  actionBarNewChatButtonDesktop: '开始新聊天',
  actionBarNewChatButtonMobile: '新建聊天',
  actionBarOngoingConvPlaceholder: '键入消息',
  attachmentLoading: '正在加载附件',
  notiUpdateBrowser: '很抱歉，我们遇到了一些问题。请尝试刷新页面并确保你的浏览器是最新的',
  bufferMessage1: '我正在使用它，请稍候',
  bufferMessage2: '请稍等',
  bufferMessage3: '花点时间思考...',
  deleteAttachment: '删除附件',
  captchaTitle: '验证身份',
  captchaDescription: '若要继续，请在下图中输入字符。',
  captchaPlaceholder: '输入字符...',
  captchaPlaceholderError: '抱歉，请重试。',
  next: '下一步',
  cancel: '取消',
  edit: '编辑',
  feedbackAccessed: '访问时间',
  feedbackSource: '源: 与必应的对话，',
  feedbackShareConversationQuery: '什么是新版必应?',
  feedbackThanksMessageV2: '感谢你的反馈。请重新开始或刷新页面。',
  messageLearnMore: '了解详细信息:',
  messageReference: '参考',
>>>>>>> upstream/master
  messageReferences: '引用',
  messagePrivacyLabel: 'Mr.🆖 提提你：誠信學習、堅拒抄襲！',
  inputRaiLabel: '',
<<<<<<< HEAD
  letsChat: '我們聊天吧',
  pause: '暫停',
  play: '開始游戲',
  speechFailedRecognitionError: '抱歉，我無法收聽你的聲音，因為語音服務器已關閉，請稍後再試。',
  speechListening: '我正在聽...',
  speechLoading: '正在等待音頻...',
  speechMediaNotReachableError: '很抱歉，我無法收聽你的聲音，因為你沒有可用的麥克風。',
  speechNoPermissionError: '你需要啟用麥克風，我才能聽到你的聲音。',
  speechAudioPlaybackError: '出錯了。',
  startOver: '重新開始',
  stop: '停止',
  welcomeContainerFAQs: '常見問題解答',
  welcomeContainerPrivacyStatement: '隱私',
  welcomeContainerUseTerms: '條款',
=======
  letsChat: '我们聊天吧',
  pause: '暂停',
  play: '开始游戏',
  readAloud: '大声朗读',
  speechFailedRecognitionError: '抱歉，我无法收听你的声音，因为语音服务器已关闭，请稍后再试。',
  speechListening: '我听着呢...',
  speechLoading: '正在等待音频...',
  speechMediaNotReachableError: '很抱歉，我无法收听你的声音，因为你没有可用的麦克风。',
  speechNoPermissionError: '你需要启用麦克风，我才能听到你的声音。',
  speechAudioPlaybackError: '出错了。',
  startOver: '重新开始',
  stop: '停止',
  welcomeContainerPrivacyStatement: '隐私',
  welcomeContainerUseTerms: '条款',
>>>>>>> upstream/master
  welcomeContainerLearnMore: '了解更多',
  welcomeMessageItemContent1: 'Do a grammar check on the text I provide. Highlight the revised words for me.',
  welcomeMessageItemContent2: 'Give me 5 different versions of the text I provide.',
  welcomeMessageItemContent3: 'Randomly generate a 15-item vocabulary list from Oxford 3000, beginning with different letters, with the order of the entries in the list randomized, in the format "**English word** [繁體中文定義] <word class symbol>: example sentence 例句中文翻譯".',
  welcomeMessageItemTitle1: '🙌 檢查英語語法',
  welcomeMessageItemTitle2: '🎨 獲取改寫建議',
  welcomeMessageItemTitle3: '🧐 生成詞彙列表',
  welcomeMessageItemLabel4: '更多創意中的新增功能：',
  warmWelcomeTitle: 'Mr.🆖 AI English Tutor',
  warmWelcomeTitleLine2: '',
<<<<<<< HEAD
  warmWelcomeAriaLabel: 'Mr.🆖 AI English Tutor',
  welcomeSubtitleText: '由Bing AI驅動的人工智能英語學習利器',
  workToggleDescription: '以及你的結果包括哪些內容',
  feedbackFirstMessage: '非常抱歉沒有幫助到你。是否可以詳細說明你不喜歡的方面?',
  feedbackPromptMessage: '感謝提醒。請提供反饋，以便我們團隊可以查看。',
  feedbackPromptGiveFeedback: '提供反饋',
  feedbackPromptGiveFeedbackAriaLabel: '提供反饋',
  feedbackPromptReportAConcern: '報告問題',
  feedbackPromptPositive: '很高興你喜歡這個答案！',
  feedbackFormTitleText: '為什麼這不起作用？',
  feedbackFormInputDefaultText: '在此處添加更多詳細信息。為了幫助保護你的隱私，請不要填入你的姓名或電子郵件地址等個人信息。',
  feedbackFormLegalText: '是否有法律或政策問題？',
  feedbackFormReportAConcern: '報告問題',
  feedbackFormNotificationTitleText: '反饋已提交',
  feedbackFormNotificationBodyText: '感謝你幫助必應改進！',
  feedbackFormThanksMessage: '感謝你提供的反饋!',
=======
  warmWelcomeAriaLabel: '欢迎使用新必应',
  welcomeSubtitleText: 'AI 支持的网上助手',
  workToggleDescription: '以及你的结果包括哪些内容',
  feedbackFirstMessage: '非常抱歉没有帮助到你。是否可以详细说明你不喜欢的方面?',
  feedbackPromptMessage: '感谢提醒。请提供反馈，以便必应团队可以查看。',
  feedbackPromptGiveFeedback: '提供反馈',
  feedbackPromptGiveFeedbackAriaLabel: '提供反馈',
  feedbackPromptPositive: '很高兴你喜欢这个答案！',
  feedbackFormTitleText: '为什么这不起作用？',
  feedbackFormInputDefaultText: '在此处添加更多详细信息。为了帮助保护你的隐私，请不要填入你的姓名或电子邮件地址等个人信息。',
  feedbackFormLegalText: '是否有法律或政策问题？',
  feedbackFormReportAConcern: '报告问题',
  feedbackFormNotificationTitleText: '反馈已提交',
  feedbackFormNotificationBodyText: '感谢你帮助必应改进！',
  feedbackFormThanksMessage: '感谢你提供的反馈!',
>>>>>>> upstream/master
  feedbackFormReturnToChatMessage: '返回到聊天',
  serpFeedbackFormTitleText: '請幫助我們改進體驗',
  serpFeedbackFormInputDefaultText: '在此處輸入反饋。為了幫助保護你的隱私，請不要填入你的姓名或電子郵件地址等個人信息。',
  serpFeedbackFormScreenshot: '包括此屏幕截圖',
  serpFeedbackFormRadioLike: '贊',
  serpFeedbackFormRadioDislike: '踩',
  serpFeedbackFormRadioConnectionIssues: '連接問題',
  serpFeedbackFormRadioSlowResponses: '回應緩慢',
  serpFeedbackFormRadioOther: '其他',
  feedbackFormUnderstandDataSharedText: '詳細了解作為診斷數據共享的內容',
  feedbackFormUserConsentText: '將提示共享到 Copilot、從 Copilot 收到的回應，以及此交互的診斷數據?',
  feedbackFormUserConsentYesText: '是',
  feedbackFormUserConsentNoText: '否',
  feedbackFormPrivacyStatement: '隱私聲明',
  feedbackFormPrivacyText: '按“提交”後，你的反饋將用於改進 Microsoft 產品和服務。組織的 IT 管理員將能夠查看和管理反饋數據。',
  compliantPositiveFeedbackFormTitleText: '向 Microsoft 提交反饋',
  compliantPositiveFeedbackQuestionText: '你喜歡哪些方面?',
  compliantPositiveFeedbackDefaultText: '請不要提供任何個人信息。',
  compliantNegativeFeedbackFormTitleText: '向 Microsoft 發送詳細反饋',
  compliantNegativeFeedbackCategoryText: '該內容是',
  compliantNegativeFeedbackQuestionText: '出了什麼問題?',
  compliantFeedbackThanksText: '感謝你提交關於 {0} 的反饋!',
  compliantFeedbackCategoryInaccurate: '不準確',
  compliantFeedbackCategoryOffensive: '冒犯性或不適宜',
  compliantFeedbackCategoryOther: '其他',
  pageTitleText: '配备 GPT-4 的必应聊天',
  submit: '提交',
<<<<<<< HEAD
  explore: '瀏覽',
  exploreMore: '瀏覽更多',
  metaInternalSearchQuery: '正在搜尋：`{0}`',
  metaInternalLoaderMessage: '正在為你產生解答...',
  metaInternalImageLoaderMessage: '分析影像: 隱私模糊會隱藏聊天中的人臉',
  compliantMetaInternalLoaderMessage: '從 {0} 產生安全解答',
  messageSharedContent: '共享內容',
  clickToView: '單擊以查看',
  more: '更多',
  expand: '展開',
  welcomeTertiaryTitleText: '使用 AI 的強大功能從 Web 中查找答案、創建書面內容等。',
  actionBarTextInputAriaLabel: '詢問必應',
  seeMore: '查看更多',
  seeLess: '查看更少',
  raiSuggestions: '這是什麼?',
  actionBarFileUploadButtonAriaLabel: '在文件中搜尋',
  actionBarStopStreamingAriaLabel: '停止流式傳輸',
  actionBarTextInputModeButtonAriaLabel: '使用鍵盤',
  actionBarSpeechInputModeButtonAriaLabel: '使用麥克風',
  actionBarVisualSearchButtonTooltip: '新增影像',
  actionBarVisualSearchButtonAriaLabel: '新增要搜尋的影像',
  actionBarVisualSearchCoachMarkTitle: '帶影像的 Mr.🆖 AI English Tutor',
  actionBarVisualSearchCoachMarkDescription: '現在你可以使用影像與 Mr.🆖 AI English Tutor 聊天！',
  actionBarVisualSearchCoachMarkImgAlt: '視覺搜尋工具提示影像',
=======
  explore: '浏览',
  exploreMore: '浏览更多',
  metaInternalSearchQuery: '正在搜索: `{0}`',
  metaInternalLoaderMessage: '正在为你生成答案...',
  metaInternalImageLoaderMessage: '分析图像: 隐私模糊会隐藏必应聊天中的人脸',
  metaInternalFileAnalyzeLoaderMessage: 'Analyzing the file {0}',
  metaInternalFileReadLoaderMessage: 'Reading the file {0}',
  compliantMetaInternalLoaderMessage: '从 {0} 生成安全答案',
  messageSharedContent: '共享内容',
  more: '更多',
  morePromptsLink: '查看更多提示',
  expand: '展开',
  welcomeTertiaryTitleText: '使用 AI 的强大功能从 Web 中查找答案、创建书面内容等。',
  actionBarTextInputAriaLabel: '询问必应',
  seeMore: '查看更多',
  seeLess: '查看更少',
  raiSuggestions: '显示了解更多建议',
  raiSuggestionsClose: '隐藏了解更多建议',
  actionBarFileUploadButtonAriaLabel: '上传高达 500 KB 的文本文件或尝试 Web URL',
  actionBarFileUploadLongContextButtonAriaLabel: '上传文本文件或尝试 Web URL',
  actionBarFileUploadButtonTooltip: '上传文本文件(最多 500 KB)或尝试 Web URL',
  actionBarFileUploadLongContextButtonTooltip: '上传文本文件或尝试 Web URL',
  actionBarTextInputModeButtonAriaLabel: '使用键盘',
  actionBarTextInputUnsupportedFileMessage: '不支持此文件类型。选择文本文件或图像文件，然后重试。',
  actionBarAddNotebookButtonTooltip: '新主题',
  actionBarAddNotebookButtonAriaLabel: '新主题',
  actionBarSpeechInputModeButtonAriaLabel: '使用麦克风',
  actionBarVisualSearchButtonTooltip: '添加图像',
  actionBarVisualSearchButtonAriaLabel: '添加要搜索的图像',
  actionBarVisualSearchCoachMarkTitle: '带图像的新必应',
  actionBarVisualSearchCoachMarkDescription: '现在你可以使用图像与必应聊天！',
  actionBarVisualSearchCoachMarkImgAlt: '视觉搜索工具提示图像',
  actionBarVisualSearchCoachMarkText: '使用 AI 分析图像',
>>>>>>> upstream/master
  actionBarSubmitButtonAriaLabel: '提交',
  actionBarCancelSpeechInputButtonAriaLabel: '取消語音輸入/讀出',
  actionBarEditModeButtonAriaLabel: '固定',
<<<<<<< HEAD
  actionBarSpeechBtnStartListeningAriaLabel: '使用麥克風',
  actionBarSpeechBtnStopListeningAriaLabel: '停止偵聽',
  actionBarSpeechBtnStopReadoutAriaLabel: '停止讀出',
  feedbackLikeButtonAriaLabel: '點贊',
  feedbackDislikeButtonAriaLabel: '不喜歡',
  feedbackOffensiveButtonAriaLabel: '標記為冒犯性',
  feedbackCopyButtonAriaLabel: '複製',
  feedbackShareButtonAriaLabel: '共享',
  messageSentAriaLabelPrefix: '已發送電子郵件',
  messageReceivedAriaLabelPrefix: '已收到消息',
  messageReportedOffensiveAndRemoved: '已刪除此消息，因為它已被舉報待審查。',
  messageAttributionsCollapseBtnAriaLabel: '折疊',
  newTopicGreet1: '謝謝你! 知道你什麼時候準備好繼續前進總是很有幫助的。我現在能為你回答什麼問題?',
  newTopicGreet2: '重新開始總是很棒。問我任何問題!',
  newTopicGreet3: '當然，我很樂意重新開始。我現在可以為你提供哪些幫助?',
  newTopicGreet4: '當然，我已準備好進行新的挑戰。我現在可以為你做什麼?',
  newTopicGreet5: '很好，讓我們來更改主題。你在想什麼?',
  newTopicGreet6: '不用擔心，我很高興嘗試一些新內容。我現在可以為你回答什麼問題?',
  newTopicGreet7: '好的，我準備好了！感謝重置。我們應該了解哪些內容？',
  newTopicGreet8: '感謝刷新！你有新的話題嗎？',
  newTopicGreet9: '明白了，讓我們重新開始。接下來應該討論什麼？',
  newTopicGreet10: '下一步！我可以為你做什麼？',
  newTopicGreet11: '好的，我已準備好新話題。我們應該一起了解哪些內容？',
  newTopicGreet12: '明白了，請繼續！感謝告訴我。我能提供什麼幫助？',
  newTopicSugg1: '教我一個新單詞',
  newTopicSugg2: '如何設定可實現的目標?',
  newTopicSugg3: '教我有關登月的信息',
  newTopicSugg4: '世界上最小的哺乳動物是什麼?',
  newTopicSugg5: '最深的海洋是哪個?',
  newTopicSugg6: '一年有多少小時?',
  newTopicSugg7: '我想學習一項新技能',
  newTopicSugg8: '讓我大笑',
  newTopicSugg9: '給我看最新新聞摘要',
  newTopicSugg10: '給我看鼓舞人心的名言',
  newTopicSugg11: '給我說個笑話',
  newTopicSugg12: '我需要有關家庭作業的幫助',
  newTopicSugg13: '尋找非虛構作品',
  newTopicSugg14: '激勵我!',
  newTopicSugg15: '向我顯示食譜',
  newTopicSugg16: '如何創建預算?',
  newTopicSugg17: '教我一個新單詞',
  newTopicSugg18: '天氣如何?',
  newTopicSugg19: '我想學習一項新技能',
  newTopicSugg20: '宇宙是如何開始的?',
  newTopicSugg21: '為什麼人類需要睡眠?',
=======
  actionBarSpeechBtnStartListeningAriaLabel: '使用麦克风',
  actionBarSpeechBtnStopListeningAriaLabel: '停止侦听',
  actionBarSpeechBtnStopReadoutAriaLabel: '停止读出',
  attachmentHasSucceded: '已成功添加附件',
  attachmentHasFailed: '附件失败',
  feedbackLikeButtonAriaLabel: '点赞',
  feedbackDislikeButtonAriaLabel: '不喜欢',
  feedbackOffensiveButtonAriaLabel: '标记为冒犯性',
  feedbackCopyButtonAriaLabel: '复制',
  feedbackRewriteButtonAriaLabel: '重写',
  feedbackShareButtonAriaLabel: '共享',
  messageReceivedAriaLabelPrefix: '已收到消息',
  messageReportedOffensiveAndRemoved: '已删除此消息，因为它已被举报待审查。',
  messageNotebookPlaceholder: '必应 AI 将在此处创建内容',
  newTopicGreet1: '谢谢你! 知道你什么时候准备好继续前进总是很有帮助的。我现在能为你回答什么问题?',
  newTopicGreet2: '重新开始总是很棒。问我任何问题!',
  newTopicGreet3: '当然，我很乐意重新开始。我现在可以为你提供哪些帮助?',
  newTopicGreet4: '当然，我已准备好进行新的挑战。我现在可以为你做什么?',
  newTopicGreet5: '很好，让我们来更改主题。你在想什么?',
  newTopicGreet6: '不用担心，我很高兴尝试一些新内容。我现在可以为你回答什么问题?',
  newTopicGreet7: '好的，我准备好了！感谢重置。我们应该了解哪些内容？',
  newTopicGreet8: '感谢刷新！你有新的话题吗？',
  newTopicGreet9: '明白了，让我们重新开始。接下来应该讨论什么？',
  newTopicGreet10: '下一步！我可以为你做什么？',
  newTopicGreet11: '好的，我已准备好新话题。我们应该一起了解哪些内容？',
  newTopicGreet12: '明白了，请继续！感谢告诉我。我能提供什么帮助？',
  newTopicSugg1: '教我一个新单词',
  newTopicSugg2: '如何设定可实现的目标?',
  newTopicSugg3: '教我有关登月的信息',
  newTopicSugg4: '世界上最小的哺乳动物是什么?',
  newTopicSugg5: '最深的海洋是哪个?',
  newTopicSugg6: '一年有多少小时?',
  newTopicSugg7: '我想学习一项新技能',
  newTopicSugg8: '让我大笑',
  newTopicSugg9: '有什么新闻?',
  newTopicSugg10: '给我看鼓舞人心的名言',
  newTopicSugg11: '给我说个笑话',
  newTopicSugg12: '我需要有关家庭作业的帮助',
  newTopicSugg13: '寻找非虚构作品',
  newTopicSugg14: '激励我!',
  newTopicSugg15: '向我显示食谱',
  newTopicSugg16: '如何创建预算?',
  newTopicSugg17: '教我一个新单词',
  newTopicSugg18: '天气如何?',
  newTopicSugg19: '我想学习一项新技能',
  newTopicSugg20: '宇宙是如何开始的?',
  newTopicSugg21: '为什么人类需要睡眠?',
>>>>>>> upstream/master
  newTopicSugg22: '如何制作蛋糕?',
  newTopicSugg23: '火烈鳥為何為粉色?',
  newTopicSugg24: '全息影像的工作原理是什麼?',
  newTopicSugg25: '金字塔是如何建成的?',
<<<<<<< HEAD
  newUserGreet: '歡迎！我是必應，我可以使用 AI 完成更多工作，例如幫助你找到完美的禮物、了解海洋或發現新音樂。告訴我你想要了解的內容！',
  newUserSugg1: '給我說個笑話',
  newUserSugg2: '玩小游戲',
  newUserSugg3: '給我講一個謎語',
  repeatUserGreet: '很高興你回來了！無論你想說什麼，我都持開放態度。我能為你做什麼？',
  repeatUserSugg1: '有什麼最新資訊',
  repeatUserSugg2: '向我展示一首詩',
  repeatUserSugg3: '給我說個笑話',
  creativeGreet: '讓我們發揮創意吧！你是否在考慮某個主題，還是即興發揮？',
  balancedGreet: '聽起來不錯，我們可以在趣事和事實中尋找平衡。如何提供幫助？',
  preciseGreet: '感謝聊天。今天我能幫你嗎？',
  creativeSugg1: '告訴我一個奇怪的事實',
  creativeSugg2: '告訴我的星座',
  creativeSugg3: '給我一個你想問的問題',
  balancedSugg1: '寫一首關於爆米花的詩',
  balancedSugg2: '蜜蜂如何釀蜜？',
  balancedSugg3: '我需要幫助制定計劃',
  preciseSugg1: '誰發明語言？',
  preciseSugg2: '我需要幫助做研究',
  preciseSugg3: '是什麼讓地球旋轉？',
  close: '關閉',
  newTopicPrompt: '通過新主題，可以開始與 Mr.🆖 AI English Tutor 就任何主題進行全新對話',
  typingIndicatorStopRespondingAriaLabel: '停止回應',
  loading: '正在加載',
  canceling: '正在取消',
  welcomeLearnSegment0: 'Mr.🆖 AI English Tutor 由 AI 提供支持，因此可能出現意外和錯誤。請確保核對事實，並',
  welcomeLearnSegment1: '讓我們一起學習。Mr.🆖 AI English Tutor 由 AI 提供支持，因此可能出現意外和錯誤。請確保核對事實，並 ',
  welcomeLearnSegment2: '共享反饋 ',
  welcomeLearnSegment3: '以便我們可以學習和改進!',
  welcomeLearnMessage: '讓我們一起學習。Mr.🆖 AI English Tutor 由可以理解並生成文本和圖像的 AI 提供支持，因此可能出現意外和錯誤。請確保核對事實，並 {0} 以便我們可以學習和改進！',
  welcomeLearnMessage2: 'Mr.🆖 AI English Tutor 會處理你在 Windows Copilot 中輸入的字詞，以生成 AI 驅動的回應，並改善你在 Windows 中的體驗。',
  welcomeLearnFeedbackSubstitute: '共享反饋',
  adsDisclaimer: '廣告不是基於工作區標識或聊天歷史記錄的目標。{0}。',
  adsDisclaimerMobileTitle: null,
  adsDisclaimerLearnMoreLink: '了解更多',
  actionBarSuspendConvPlaceHolder: '已為挂起的帳戶禁用消息傳遞',
  actionBarNewlineTooltip: '使用 Shift+Enter 為較長的消息創建換行符',
  notiReConnect: '出錯了。',
  notiChatEnd: '聊天主題已結束。',
  notiRestartChat: '在 {0} 小時內開始新主題',
  notificationAttemptingToReconnect: '正在嘗試重新連接...',
  notificationProcessing: '正在嘗試連接，請稍候',
  notificationLostConnection: '很抱歉，你的連接似乎已斷開。',
  notificationLostConnectionCta: '是否要嘗試重新連接？',
  sydneySapphireCopyToClipboardText: '已複製到剪貼板。',
  sydneySapphireUpsellContent: '現在就獲取使用新 AI 驅動的必應應用程序吧!',
  sydneySapphireWelcomeText: '歡迎回來! 下面是此頁面的一些內容。',
  sydneySapphireConsentTitleText: '使用新必應提升瀏覽',
  sydneySapphireConsentMessageText: '允許 Microsoft 訪問你的瀏覽器 Web 內容，以便使用 AI 生成的摘要和新必應的熱點功能更好地個性化你的體驗。了解更多信息',
  sydneySapphireConsentConfirmText: '確認',
  sydneySapphireConsentDenyText: '拒絕',
  sydneySapphireSummarizeSuggestionShip: '匯總',
  sydneySapphireExplainSuggestionShip: '解釋',
  sydneySapphireKeyTakeawaysSuggestionShip: '關鍵要點',
  sydneySapphireAskMeaningSuggestionChip: 'What does that mean?',
  sydneySapphireRelevantInformationSuggestionChip: 'Give me relevant information about this',
  sydneySapphireOverviewSuggestionChip: 'Could you provide a brief overview?',
  sydneySapphireGenerateSummaryMessage: '生成此頁面的摘要',
  sydneySapphireContextGreet: 'It looks like you asked about {0}. What do you want to know about this?',
  sydneySapphireGPT4Greet: '讓我們通過 GPT-4 🎉 獲得創意。在發揮創意的同時，回應速度可能會變慢。你是否在考慮某個主題，還是應該為其建立分支?',
  typingIndicatorStopStreamingAriaLabel: '停止流式傳輸',
  sydneyCarouselCollapse: '折疊',
  sydneyCarouselTitle: '最近的聊天主題',
  messageActionsCopy: '複製',
  messageActionsCopying: '正在複製',
  messageActionsCopied: '已複製',
  messageActionsCopyError: '錯誤',
  messageActionsReport: '報告',
  tooltipPositive: '點贊',
  tooltipNegative: '不喜歡',
  tooltipShare: '共享',
  tooltipMore: '更多',
  tooltipSendToPhone: '在手機上繼續',
  codeDisclaimer: '此代碼由 AI 生成。仔細查看和使用。有關詳細信息，請{0}。',
  codeDisclaimerLinkLabel: '訪問我們的常見問題解答',
  exportTitle: '導出',
  exportTextTitle: '下載為文本 (.txt)',
  exportPdfTitle: '以 PDF (.pdf) 格式下載',
  exportWordTitle: '以 Word (.docx) 格式下載',
  exportWordOnlineTitle: '導出到 Word Web 應用',
  exportExcelTitle: '以 Excel (.xlsx) 格式下載',
  exportExcelOnlineTitle: '導出到 Excel Web 應用',
  exportToastViewButtonLabel: '查看',
  exportSuccessToastTitle: '已導出文件。某些格式和圖像可能無法導出。',
  exportErrorToastTitle: '導出失敗',
  exportLoadingToastTitle: '正在導出...',
  exportedFileUserTitle: '用戶',
  exportedFileBotTitle: 'Mr.🆖 AI English Tutor',
  feedbackExportButtonAriaLabel: '導出',
  feedbackExportPdfButtonAriaLabel: 'PDF',
  feedbackExportTextButtonAriaLabel: 'Text',
  feedbackExportWordButtonAriaLabel: 'Word',
  tooltipExport: '導出',
  messageActionsExportPdf: 'PDF',
  messageActionsExportText: 'Text',
  messageActionsExportWord: 'Word',
  exportOnlineWordButtonLabel: '聯機 Word',
  exportLocalWordButtonLabel: '下載',
  exportTableToExcelButtonTooltip: '在瀏覽器中打開',
  mobileUpsellMessage1: '掃描此 QR 碼以在移動應用上繼續此對話',
  mobileUpsellTitle1: '在手機上繼續',
  visualSearchMobileUpsellLabel: 'Use Bing app on phone',
  mobileUpsellTitle2: 'Use Bing app to take photo',
  mobileUpsellMessage2: 'Scan QR code to take this photo with the Bing app on your mobile device',
  sydneySapphireUpsellConsentTitle: '是否繼續從桌面聊天?',
  sydneySapphireUpsellConsentMessage: '你在其他裝置上有一個活動的聊天。是否要繼續此對話?',
  sydneySapphireUpsellConsentConfirm: '是',
  sydneySapphireUpsellConsentDeny: '不，謝謝',
  actionBarAutoSuggestTab: 'Tab',
  actionBarAutoSuggestTap: '點擊',
  actionBarKeyboardHint: '輸入',
  feedbackShareAnswer: '查看此答案',
  feedbackShareGenerated: '查看生成的內容',
  feedbackShareTitleFormat: '{0} | {1}',
  feedbackShowTonesButtonAriaLabel: '顯示所有音調',
  feedbackHideTonesButtonAriaLabel: '隱藏所有色調',
  feedbackHidePreciseToneButtonAriaLabel: '隱藏精確',
  feedbackShareErrorToast: '共享失敗。',
  serpfeedback: '反饋',
  shareConversation: '共享整個對話',
  speechAuthenticationError: '身份驗証失敗。請稍後重試。',
  speechUnknownError: '出錯了。',
  refresh: '刷新',
  feedbackShareContent: '下面是我使用新的必應（全球首個 AI支持的應答引擎）生成的答案。單擊可查看完整答案，然後請你也來試一試。',
  fileUploadFlyoutInputboxAriaLabel: '貼上網頁 URL',
  fileUploadFlyoutTitle: '新增文本文件',
  fileUploadFlyoutUploadButtonLabel: '從此裝置上傳',
  fileUploadGenericErrorMessage: '抱歉 - 上傳似乎失敗。請重試',
  preview: '模式',
  toneSelectorDescription: '',
  toneSelectorCreative: '有創造力',
  toneSelectorCreativeModifier: '更',
  toneSelectorBalanced: '平衡',
  toneSelectorBalancedModifier: '更',
  toneSelectorPrecise: '精確',
  toneSelectorPreciseModifier: '更',
  toneSelectorMoreCreative: '更\\r\\n有創造力',
=======
  newUserGreet: '很高兴认识你！我是必应，我不仅仅是一个搜索引擎。我可以帮助你规划群、写一个朋友或询问宇宙。你想要探索什么？',
  newUserSugg1: '写一首诗',
  newUserSugg2: '玩小游戏',
  newUserSugg3: '给我说个笑话',
  repeatUserGreet: '又见面了。我很乐意为你提供任何帮助。如何为你效劳，改进你的一天?',
  repeatUserSugg1: '生成故事',
  repeatUserSugg2: '告诉我一个事实',
  repeatUserSugg3: '你可以做什么?',
  creativeGreet: '好吧!这就是创造力。我能帮什么忙？',
  balancedGreet: '好的，我们来查找答案并聊会天。我可以为你做什么？',
  preciseGreet: '感谢聊天。今天我能帮你吗？',
  creativeSugg1: '告诉我的星座',
  creativeSugg2: '让我们写一首节拍诗',
  creativeSugg3: '给我一个你想问的问题',
  balancedSugg1: '给我个周末度假的主意',
  balancedSugg2: '附近哪里可以看到星星？',
  balancedSugg3: '哪种花最香？',
  preciseSugg1: '我需要帮助做研究',
  preciseSugg2: '给我列出今晚晚餐的购物清单',
  preciseSugg3: '谁发明语言？',
  close: '关闭',
  newTopicPrompt: '通过新聊天，可以开始与必应就任何主题进行全新对话',
  typingIndicatorStopRespondingAriaLabel: '停止响应',
  loading: '正在加载',
  canceling: '正在取消',
  welcomeLearnMessage: '必应由 AI 提供支持，因此可能会出现意外和错误。请分享反馈，以便我们可以改进!',
  welcomeLearnMessage2: 'Bing Chat 会处理你在Windows Copilot 中输入的字词，以生成 AI 驱动的响应，并改善你在 Windows 中的体验。',
  welcomeLearnFeedbackSubstitute: '共享反馈',
  adsDisclaimer: '广告不是基于工作区标识或聊天历史记录的目标。{0}。',
  adsDisclaimerLearnMoreLink: '了解更多',
  actionBarNewlineTooltip: '使用 Shift+Enter 为较长的消息创建换行符',
  notiChatEnd: '聊天主题已结束。',
  notiRestartChat: '在 {0} 小时内开始新主题',
  notificationAttemptingToReconnect: '正在尝试重新连接...',
  notificationProcessing: '正在尝试连接，请稍候',
  notificationLostConnection: '很抱歉，你的连接似乎已断开。',
  notificationLostConnectionCta: '是否要尝试重新连接？',
  sydneySapphireConsentDenyText: '拒绝',
  typingIndicatorStopStreamingAriaLabel: '停止流式传输',
  sydneyCarouselCollapse: '折叠',
  sydneyCarouselTitle: '最近的聊天主题',
  messageActionsCopy: '复制',
  messageActionsCopying: '正在复制',
  messageActionsCopied: '已复制',
  messageActionsCopyError: '错误',
  messageActionsReport: '报告',
  tooltipPositive: '点赞',
  tooltipNegative: '不喜欢',
  tooltipShare: '共享',
  tooltipMore: '更多',
  tooltipSendToPhone: '在手机上继续',
  codeDisclaimer: 'AI 生成的代码。仔细查看和使用。 {0}.',
  codeDisclaimerLinkLabel: '有关常见问题解答的详细信息',
  exportTitle: '导出',
  exportTextTitle: '下载为文本(.txt)',
  exportPdfTitle: '以 PDF (.pdf)格式下载',
  exportWordTitle: '下载为文档(.docx)',
  exportWordOnlineTitle: '在 Word 中编辑',
  exportExcelTitle: '下载为工作簿(.xlsx)',
  exportExcelOnlineTitle: '在 Excel 中编辑',
  exportTableTitle: '表格',
  exportToastViewButtonLabel: '查看',
  exportSuccessToastTitle: '已导出文件。某些格式和图像可能无法导出。',
  exportErrorToastTitle: '导出失败',
  exportLoadingToastTitle: '正在导出...',
  exportedFileUserTitle: '用户',
  exportedFileBotTitle: '必应',
  exportedFileSourceTitle: '源',
  mobileUpsellMessage1: '扫描此 QR 码以在移动必应应用上继续此对话',
  mobileUpsellTitle1: '在手机上继续',
  visualSearchMobileUpsellLabel: '在手机上使用必应应用',
  mobileUpsellTitle2: '使用必应应用拍摄照片',
  mobileUpsellMessage2: '扫描 QR 码以在移动设备上使用必应应用拍摄此照片',
  actionBarAutoSuggestTab: 'Tab',
  actionBarAutoSuggestTap: '点击',
  actionBarKeyboardHint: '输入',
  feedbackShareAnswer: '查看此必应答案',
  feedbackShareGenerated: '查看我使用必应生成的内容',
  feedbackShowTonesButtonAriaLabel: '显示所有音调',
  feedbackHideTonesButtonAriaLabel: '隐藏所有色调',
  feedbackHidePreciseToneButtonAriaLabel: '隐藏精确',
  feedbackShareErrorToast: '共享失败。',
  serpfeedback: '反馈',
  shareConversation: '共享整个对话',
  speechAuthenticationError: '身份验证失败。请稍后重试。',
  speechOnlineNotification: '语音输入由 Microsoft 联机服务处理，不会进行收集或存储。',
  speechUnknownError: '出错了。',
  refresh: '刷新',
  feedbackShareContent: '下面是我使用新的必应（全球首个 AI支持的应答引擎）生成的答案。单击可查看完整答案，然后请你也来试一试。',
  fileUploadDragAndDropLabel: '在此处删除图像或文件',
  fileUploadUnsupportedFileMessage: '此文件类型不受支持。选择文本文件，然后重试。',
  fileUploadMaxSizeLimitErrorMessage: '文件大小已超限。只能上传高达 500KB 的文件。',
  fileUploadMaxSizeLimitLongContextErrorMessage: '文件大小已超限。只能上传大小不超过 10MB 的文件。',
  fileUploadMaxSizeLongContextErrorMessage: 'File size exceeded. You can only upload a file up to {0}MB.',
  fileUploadTextFileUploadErrorMessage: '无法上传文件。',
  fileUploadWebPageInfoUploadErrorMessage: '无法从网页中提取内容。',
  fileUploadFlyoutInputboxAriaLabel: '粘贴网页 URL',
  fileUploadFlyoutTitle: '添加文本文件',
  fileUploadFlyoutUploadButtonLabel: '从此设备上传',
  fileUploadGenericErrorMessage: '无法上传该文件。请重试',
  preview: '预览',
  toneSelectorDescription: '选择对话样式',
  toneSelectorMoreCreative: '更\\r\\n有创造力',
>>>>>>> upstream/master
  toneSelectorMoreBalanced: '更\\r\\n平衡',
  toneSelectorMorePrecise: '更\\r\\n精確',
  toneSelectorFaster: '更快',
  toneSelectorWithGPT4: '使用 GPT-4',
<<<<<<< HEAD
  notificationMaxTurnsPerDay: '很抱歉，你已達到可在 24 小時內發送到必應的郵件限制。請稍後回來查看!',
  notificationMaxTurnsPerConversation: '很抱歉，此對話已達到其限制。使用“新主題”按鈕清除本次對話內容並進行更多聊天。',
  notificationMaxTurnsForMuidUsers: '你已達到本次的對話限制。',
  notificationMaxTurnsForInPrivateUsers: '你已達到 inPrivate 模式的會話限制。打開非 inPrivate 窗口以繼續聊天',
  notificationUnauthorizedMuidUsersCta: '使用“新主題”按鈕清除本次對話內容並進行更多聊天。',
  notificationChatEnterMuidUsers: '登錄以提出更多問題並進行更長的對話。',
  muidUsersTermsCond1: '通過單擊“開始使用”，並繼續與 Mr.🆖 AI English Tutor 交互，即表示你接受',
  muidUsersTermsCond1Inline: '通過繼續與 Mr.🆖 AI English Tutor 交互，你將接受 ',
  muidUsersTermsCond2: '並確認你已查看',
  muidUsersPrivacyStatement: '隱私聲明',
  muidUsersTermsOfUse: '使用條款',
  muidUserGetStartedText: '開始使用',
  muidUserContinueText: '繼續',
  welcomeMobSugg1: 'Mr.🆖 AI English Tutor 如何使用 AI?',
  welcomeMobSugg2: 'Mr.🆖 AI English Tutor 還可以做什麼？',
  welcomeMobSugg3: '科技領域的最新消息是什麼？',
  of: 'of',
  notificationResetConversation: '很抱歉，似乎出現錯誤。',
  notificationResetConversationCta: '讓我們重新開始吧。',
  toneSelectorCreativeTooltip: '清除對話並開始原創和富有想象力的聊天',
  toneSelectorBalancedTooltip: '清除對話並開始一個信息豐富且友好的聊天',
  toneSelectorPreciseTooltip: '清除對話並開始簡潔直截了當的聊天',
  toneSelectorSuppressedTooltip: '暫時不可使用。請稍後再試!',
  notificationDisengaged: '也許該換個新話題了。',
  notificationDisengagedCta: '',
  notificationForbidden: '很抱歉，你似乎不再有權訪問此功能。請幾天後再次查看。',
  notificationTooManyRequests: '很抱歉，現在需求量非常大。請稍後重試。',
  notificationUnauthorized: '很抱歉，你似乎已注銷。',
  notificationUnauthorizedCta: '請重新登錄。',
  notificationMessageError: '上一條消息似乎已中斷。',
  notificationSharedTip: '此對話\u003cstrong\u003e“{0}”\u003c/strong\u003e已於 {1} 與你共享',
  mmAnswerPrompt1: '我總算給你找到了一些東西! 看一看。',
  mmAnswerPrompt2: '我終於找到了一些東西! 這是你要找的嗎?',
  mmAnswerPrompt3: '抱歉搞混了，我確實給你找到了一些東西。給你!',
  mmAnswerPrompt4: '嘿! 我確實找到了一些東西，這是你想要的嗎?',
  mmAnswerPrompt5: '看! 我找到了一些適合你的內容。',
  mmAnswerPrompt6: '等等，在這裡! 抱歉弄亂了，看一下吧。',
  mmAnswerPrompt7: '我找到你要的媒體了! 抱歉耽擱了。',
  signInCta: '登錄 ',
  signInDescription: ' 以提出更多問題並進行更長的對話',
  signInDescriptionInPrivate: '打開非 inPrivate 窗口，以便進行更長的對話或提出更多問題',
  copyCodeSuccessToastTitle: '已複製到剪貼板',
  copyCodeButtonTooltip: '複製',
  copyCodeButtonSuccessTooltip: '已複製',
  threadsSharedOnDate: '於 {0} 共享',
  threadsMore: '更多',
  threadsExportPanelTitle: '選擇格式',
  threadsExportPanelAriaLabel: '選擇',
  threadsAADMSARedirectConfirm: '切換用戶配置',
  threadsAADMSARedirectDescription: '正在使用 Microsoft 帳戶保存你的對話歷史記錄。下次使用個人帳戶登錄時，它將在此處顯示。',
=======
  notificationClientIdChangedInNotebook: '你的笔记本已过期。',
  notificationClientIdChangedInNotebookCta: '开始新主题',
  notificationMaxTurnsPerDay: '很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看!',
  notificationMaxTurnsPerConversation: '很抱歉，此对话已达到其限制。使用“扫除”按钮清除此内容并进行更多聊天。',
  notificationMaxTurnsPerConversationInNotebook: '很抱歉，我想我们需要继续操作!使用左侧的“新主题”按钮清除内容并重新开始。',
  notificationMaxTurnsForMuidUsers: '你已达到今天的对话限制。',
  notificationMaxTurnsForInPrivateUsers: '你已达到 inPrivate 模式的会话限制。打开非 inPrivate 窗口以继续聊天',
  notificationUnauthorizedMuidUsersCta: '登录以继续你的聊天。',
  muidUserHeaderText: '',
  muidUsersTermsCond1: '通过单击“开始使用”，并继续与必应交互，即表示你接受',
  muidUsersTermsCond1Inline: '通过继续与必应交互，你将接受 ',
  muidUsersTermsCond2: '并确认你已查看',
  muidUsersPrivacyStatement: '隐私声明',
  muidUsersTermsOfUse: '使用条款',
  muidUserGetStartedText: '开始使用',
  muidUserContinueText: '继续',
  welcomeMobSugg1: '必应如何使用 AI?',
  welcomeMobSugg2: '必应还可以做什么？',
  welcomeMobSugg3: '科技领域的最新消息是什么？',
  of: '共',
  notificationResetConversation: '很抱歉，似乎出现错误。',
  notificationResetConversationCta: '让我们重新开始吧。',
  toneSelectorCreativeTooltip: '清除对话并开始原创和富有想象力的聊天',
  toneSelectorBalancedTooltip: '清除对话并开始一个信息丰富且友好的聊天',
  toneSelectorPreciseTooltip: '清除对话并开始简洁直截了当的聊天',
  toneSelectorSuppressedTooltip: '暂时不可用。请稍后再试!',
  notificationDisengaged: '也许该换个新话题了。',
  notificationForbidden: '很抱歉，你似乎不再有权访问此功能。请几天后再次查看。',
  notificationTooManyRequests: '很抱歉，现在需求量非常大。请稍后重试。',
  notificationUnauthorized: '很抱歉，你似乎已注销。',
  notificationUnauthorizedCta: '请重新登录。',
  notificationUnauthorizedMissingDOB: '可能需要确认你的出生日期才能继续聊天。',
  notificationUnauthorizedMissingDOBCta: '在此处更新你的帐户。',
  notificationUnauthorizedChildUser: '很抱歉，必应聊天不适用于此帐户。',
  notificationUnauthorizedChildUserCta: '在 bing.com 上浏览 Web!',
  notificationMessageError: '上一条消息似乎已中断。',
  notificationMessageErrorInNotebook: '你上次的提示似乎已中断。',
  notificationSharedTip: '此对话\u003cstrong\u003e“{0}”\u003c/strong\u003e已于 {1} 与你共享',
  notificationNetworkOffline: '抱歉，你尚未连接。请检查你的网络连接并重试。',
  notificationAutoRefreshConversation: '出错了。正在解决，请稍候。',
  notificationAutoResendOnConnectionError: '你的连接暂时丢失。正在重新连接，请稍候。',
  notificationAutoRecoverOnMessageError: '很抱歉，你最后一封邮件似乎已中断。正在解决，请稍候。',
  notificationAutoRecoverOnMessageErrorInNotebook: '很抱歉，你最后一封邮件似乎已中断。正在解决，请稍候。',
  notificationContinueRecovering: '我仍在解决问题，请稍候。',
  signInCta: '登录 ',
  signInDescription: ' 以提出更多问题并进行更长的对话',
  signInDescriptionInPrivate: '打开非 inPrivate 窗口，以便进行更长的对话或提出更多问题',
  copyCodeButtonTooltip: '复制',
  threadsSharedOnDate: '于 {0} 共享',
  threadsMore: '更多',
  threadsExportPanelTitle: '选择格式',
  threadsExportPanelAriaLabel: '选择',
  threadsAADMSARedirectConfirm: '切换用户配置',
  threadsAADMSARedirectDescription: '正在使用 Microsoft 帐户保存你的对话历史记录。下次使用个人帐户登录时，它将在此处显示。',
  privateThreadConvDefaultTitle: '未保存的对话',
>>>>>>> upstream/master
  threadsCancel: '取消',
  threadsChatHistory: '聊天記錄',
  threadsConfirm: '確認',
  threadsDaysAgo: '{0} 天前',
  threadsDefaultChatName: '無標題的聊天',
  threadsDelete: '刪除',
  threadsDescription: 'AI 支持的助手現可自動保存聊天。你可以從任何設備、桌面或移動設備訪問聊天，無縫地繼續。',
  threadsDescriptionNote: '請注意，除非專門保存，否則所有聊天將在 90 天內自動刪除。',
  threadsEdit: '重命名',
  threadsLoad: '加載聊天',
  threadsMinimizeRecent: '最小化最近的聊天',
  threadsMinimizeSaved: '最小化保存的聊天',
  threadsPreview: '預覽',
  threadsPreviewText: '跳回最近聊天',
  threadsRecentTitle: '最近的活動',
  threadsRecentTitleShort: '最近使用',
  threadsSavedTitle: '已保存',
  threadsSeeAllRecent: '查看所有最近的聊天',
  threadsSeeAllSaved: '查看所有保存的聊天',
  threadsTitle: '聊天',
  threadsTitleForFlux: '菜單',
  threadsYesterday: '昨天',
  threads2TLastAccessed: '上次應答時間',
  threads2TInfoChanged: '此信息可能已更改，因為',
  threads2TArchivedText: '屏幕截圖',
  threads2TReloadDescription: '單擊“重新加載”以顯示來自 Web 的最新信息',
  threads2TFailedSearch: '請參閱最新 Bing.com',
  threads2TReload: '搜索 Bing.com',
<<<<<<< HEAD
  injectedActionCardTitle: '就此頁面進行聊天?',
  injectedActionCardNewTopicTitle: '開始有關此頁面的新聊天?',
  injectedActionCardConfirm: '發送',
=======
  injectedActionCardTitle: '就此页面进行聊天?',
  injectedActionCardConfirm: '发送',
>>>>>>> upstream/master
  injectedActionCardDeny: '忽略',
  webPageContextPrefix: '已訪問網站',
  useGPT4SwitchLabel: '使用 GPT-4',
  zeroInputSuggestionFallback1: 'Randomly generate a 15-item vocabulary list from Oxford 3000, beginning with different letters, with the order of the entries in the list randomized, in the format "**English word** [繁體中文定義] <word class symbol>: example sentence 例句中文翻譯".',
  zeroInputSuggestionFallback2: '對於一個預算有限的六口之家來說，會首選哪三款車型？',
  zeroInputSuggestionFallback3: '寫一個我的同事會覺得有趣的笑話',
  zeroInputSuggestionFallback4: 'Do a grammar check on the text I provide. Highlight the revised words for me.',
  zeroInputSuggestionFallback5: '撰寫關於魚和青蛙尋找愛的原創寓言故事',
  zeroInputSuggestionFallback6: 'Give me 5 different versions of the text I provide.',
  zeroInputSuggestionFallback7: '為具有諷刺風格的新社交媒體平台創建一個口號',
  zeroInputSuggestionCategory1: '生成詞彙列表',
  zeroInputSuggestionCategory2: '比較',
  zeroInputSuggestionCategory3: '大笑',
<<<<<<< HEAD
  zeroInputSuggestionCategory4: '檢查英語語法',
  zeroInputSuggestionCategory5: '寫入',
  zeroInputSuggestionCategory6: '獲取改寫建議',
  zeroInputSuggestionCategory7: '創建',
  discoverMessageItemTitle: '📝 一起重寫文本',
  discoverMessageItemContent: '嘗試從頁面中選擇文本以查看我們可以一起執行的操作',
  pluginTitle: '插件',
  bookNowWithOpenTable: '立即使用 OpenTable 預訂',
  scrollLeft: '向左滾動',
  scrollRight: '向右滾動',
  personalizationConsentTitleText: '✨ 對了，你想要個性化的答案嗎?✨',
  personalizationConsentContentText1: '共享聊天歷史記錄時，會根據你和你的興趣定製回覆。',
  personalizationConsentContentText2: '。',
  personalizationConsentLearnMoreText: '了解有關個性化答案的詳細信息',
  personalizationConsentEnableText: '是的，我想要!',
  personalizationConsentAskAgainLaterText: '以後再說',
  personalizationConsentDisableText: '不，謝謝',
  personalizationConsentStatusPositiveText: '已啟用個性化。',
  personalizationConsentStatusNegativeText: '未啟用個性化。',
  personalizationConsentSettingsText1: '若要修改，請訪問',
  personalizationConsentSettingsLinkText: '聊天設置',
  personalizationConsentSettingsText2: '頁面',
  pluginEnabledPlugin: '已啟用',
=======
  zeroInputSuggestionCategory4: '聊天',
  zeroInputSuggestionCategory5: '写入',
  zeroInputSuggestionCategory6: '组织',
  zeroInputSuggestionCategory7: '创建',
  zeroInputDescription: '必应是 AI 支持的网上助手',
  discoverMessageItemTitle: '📝 一起重写文本',
  discoverMessageItemContent: '尝试从页面中选择文本以查看我们可以一起执行的操作',
  pluginTitle: '插件',
  bookNowWithOpenTable: '立即使用 OpenTable 预订',
  scrollLeft: '向左滚动',
  scrollRight: '向右滚动',
  responses: 'responses',
  personalizationConsentTitleText: '已为你设置个性化对话',
  personalizationConsentTitleTextEu: '已为你设置个性化对话',
  personalizationConsentContentText1: '必应使用聊天历史记录中的 Insights 使对话成为独一无二的对话。',
  personalizationConsentContentText1Eu: '共享聊天历史记录时，必应会根据你和你的兴趣定制回复。',
  personalizationConsentContentText2: '。',
  personalizationConsentLearnMoreText: '在我们的常见问题解答中了解详细信息',
  personalizationConsentLearnMoreTextEu: '了解有关个性化的详细信息',
  personalizationConsentContentSettingsText: '随时在必应设置中关闭个性化设置。 ',
  personalizationConsentStatusPositiveText: '已启用个性化。',
  personalizationConsentStatusNegativeText: '未启用个性化。',
  personalizationConsentSettingsText1: '若要修改，请访问',
  personalizationConsentSettingsLinkText: '必应聊天设置',
  personalizationConsentSettingsText2: '页面',
  personalizationConsentTurnOnText: '打开',
  personalizationConsentTurnOffText: '不打开',
  pluginEnabledPlugin: '已启用',
>>>>>>> upstream/master
  pluginEnabledNumber: '{0} / {1}',
  pluginStartNewTopic: '開始新主題',
  pluginToChangePlugin: '更改插件',
<<<<<<< HEAD
  pluginNotificationMaxExceeded: '已啟用的最大插件數',
  pluginNotificationExclusive: '{0} 與 {1} 太相似。請選擇一個',
  pluginTerms: '使用條款',
  pluginPrivacy: '隱私策略',
  pluginPanelFreTitle: '插件現在可用',
=======
  pluginNotificationMaxExceeded: '已启用的最大插件数',
  pluginNotificationMaxExceededV2: '已启用最大数量的插件。',
  pluginNotificationExclusive: '{0} 与 {1} 太相似。请选择一个',
  pluginNotificationExclusiveV2: '{0} 和 {1} 可以起到类似的作用。请选择一个。',
  pluginTerms: '使用条款',
  pluginPrivacy: '隐私策略',
  pluginPanelFreTitle: '插件现在可用',
>>>>>>> upstream/master
  pluginPanelFreTextLabel: '新建:',
  pluginPanelFreText: '打開插件，幫助你從喜歡的品牌中查找餐廳預訂、航班等。',
  pluginPanelFreDismiss: '忽略',
  pluginPanelAlertTitle: '插件在“平衡”模式下不可用',
<<<<<<< HEAD
  pluginPanelAlertCta: '重置對話 ',
  pluginPanelAlertSubtitle: '並使用“更多創意”或“更精確”對話樣式，然後重試。',
  pluginLimitationTitle: '將插件與必應 AI 配合使用',
  pluginLimitationMax: '最多為任意一個對話線程選擇 3 個插件。',
  pluginLimitationLock: '在選擇“新建主題”進行更改之前，插件會鎖定到對話中。',
  pluginShowMore: '展開',
  pluginPanelNolimit: '禁用 {0} 不會影響插件限制',
  threadsToggleExpansion: '切換擴展',
  threadsEnabledPlugins: '已啟用插件:',
  bingSearchDisabled: '**已禁用**。',
  bingSearchDisabledforMessage: '已禁用',
  activateSearch: '啟動新主題並激活搜索',
  visualSearchFlyoutTitle: '新增影像',
  visualSearchGenericErrorMessage: '無法上傳該文件。請重試。',
  visualSearchUnsupportedFileMessage: '不支持此文件類型。選擇影像文件，然後重試。',
  visualSearchInvalidUrlMessage: '抱歉 - 你提供的 URL 似乎無效。請重試',
  visualSearchFlyoutInputboxAriaLabel: '貼上圖片或連結',
  visualSearchFlyoutTakePhotoButtonLabel: '拍攝相片',
  visualSearchDragAndDropLabel: '把圖片拖到此處',
  visualSearchFlyoutUploadButtonLabel: '從此裝置上傳',
  raiDisclaimerLabel: 'AI 產生的內容可能不正確',
  slimHeaderTitle: '查看 AI 支持的解答',
  starterPageTitle: '由Bing AI驅動的人工智能英語學習利器',
  starterDescription: '用你自己的語言與我聊天。如果感到卡住，請選擇以下開場白之一，以觀察我是如何運作的：',
  starterSubtitle1: '進行對話',
  starterSubtitle2: '釋放你的創造力',
=======
  pluginPanelAlertCta: '重置对话 ',
  pluginPanelAlertSubtitle: '并使用“更多创意”或“更精确”对话样式，然后重试。',
  pluginLimitationDataShared: '将与你选择的插件共享数据。',
  pluginLimitationTitle: '将插件与必应 AI 配合使用',
  pluginLimitationMax: '最多为任意一个对话线程选择 3 个插件。',
  pluginLimitationMaxV2: '为对话最多选择 {0} 个插件。',
  pluginLimitationLock: '在选择“新建主题”进行更改之前，插件会锁定到对话中。',
  pluginLimitationLockV2: '若要在开始对话后更改插件，请选择 {0}。',
  pluginPanelNolimit: '禁用 {0} 不会影响插件限制',
  activatetoUsePlugins: '激活 {0} 以使用插件',
  threadsToggleExpansion: '切换扩展',
  threadsEnabledPlugins: '已启用插件:',
  bingSearchDisabled: '搜索**已禁用**。',
  bingSearchDisabledforMessage: '搜索已禁用',
  activateSearch: '启动新主题并激活搜索',
  visualSearchFlyoutTitle: '添加图像',
  visualSearchGenericErrorMessage: '无法上传该文件。请重试。',
  visualSearchUnsupportedFileMessage: '不支持此文件类型。选择图像文件，然后重试。',
  visualSearchInvalidUrlMessage: '抱歉 - 你提供的 URL 似乎无效。请重试',
  visualSearchFlyoutInputboxAriaLabel: '粘贴图像或链接',
  visualSearchFlyoutTakePhotoButtonLabel: '拍照',
  visualSearchDragAndDropLabel: '将图片拖至此处',
  visualSearchFlyoutUploadButtonLabel: '从此设备上传',
  raiDisclaimerLabel: 'AI 生成的内容可能不正确',
  slimHeaderTitle: '查看 AI 支持的新必应的解答',
  starterPageTitle: '必应是 AI 支持的网上助手',
  starterDescription: '用你自己的语言与必应聊天。如果感到卡住，请选择以下开场白之一，以观察必应是如何运作的：',
  starterSubtitle1: '进行对话',
  starterSubtitle2: '释放你的创造力',
>>>>>>> upstream/master
  starterSubtitle3: '更智能地搜索',
  starterContent1: '像日常聊天一樣使用自然語句並詢問后續內容時，效果最佳',
  starterContent2: '無論是用圖像還是文字，我可以通過讓你的願景變為現實來激發你的創造力',
  starterContent3: '與我聊天是一種新搜索方式。讓我匯總 Web 內容並提供答案',
  starterChatQuery1: '你認為其他行星上有生命嗎？地球的獨特之處是什麼？',
  starterChatQuery2: '如果我睡眠遇到問題，但隻在夏天發生，是怎麼回事？',
  starterChatQuery3: '我想開辟一個花園，但我對此一無所知。第一步需要做什麼？',
  starterChatQuery4: '你認為鱷魚或灰熊會在搏斗中獲勝嗎？',
  starterChatQuery5: '我最近讀了很多非虛構類書籍。你能幫我找到我喜歡的主題的虛構類版本嗎？',
  starterChatQuery6: '讓我們進行一次對話，其中你說的所有內容都是用表情符號編寫的。',
  starterChatQuery7: '我一直在考慮搬到一個新的地方。你認為我應該去哪兒？',
  starterChatQuery8: '我曾經寫過日記，但最近經常偷懶。我如何才能保持習慣？',
  starterChatQuery9: '你是否會像人類一樣做夢？你會夢到什麼？',
  starterChatQuery10: '是否可能同時發生地震、海嘯和火山噴發？',
  starterCreateQuery1: '我有一隻黑毛的小狗，除了肚子上的毛是白色的。請將它畫成卡通形象。',
  starterCreateQuery2: '為我的 3 歲的侄女寫一個睡前故事。她喜歡馬和魔法，而且我認為這個故事應該押韻”',
  starterCreateQuery3: '用一位高傲自大的教授的語氣撰寫一篇短文，來証明月亮比太陽更好',
  starterCreateQuery4: '用印象派風格畫一隻在冰山上晒太陽的北極熊。它還應該在喝檸檬水',
  starterCreateQuery5: '讓我們來創造一種顏色，並撰寫一個社交媒體帖子向全世界介紹它',
  starterCreateQuery6: '作為由 Christian Bale 扮演的蝙蝠俠，請告訴我如何騎著摩托車應對交通',
  starterCreateQuery7: '用一位在家釀酒並引發小型爆炸的爸爸的語氣，為一個新的啤酒品牌制作銷售宣傳',
  starterCreateQuery8: '為一家咖啡館設計一副海報，其中包含日落並充分利用空間',
  starterCreateQuery9: '畫一隻身為湖上躉船船長的長頸鹿',
  starterCreateQuery10: '為一篇有關女權主義文學歷史的論文撰寫簡介段落，並為我提供五個寫作提示以繼續',
  starterCompareQuery1: '為我找一份提拉米蘇的菜譜，為我制作一個購物清單，然后進行排列，以便我可以在商店中快速找到配料',
  starterCompareQuery2: '為我提供的今天的本地新聞匯報，不包括體育內容”',
  starterCompareQuery3: '用五個要點總結最新的 AI 研究，並得出接下來的發展趨勢的結論',
  starterCompareQuery4: '創建一個表格，用來按品牌、價格、安全功能和可能的附加設備比較最佳電動車',
  starterCompareQuery5: '這附近有兒童游樂場的最近的公園在哪裡？',
  starterCompareQuery6: '為我晚上要做的意大利菜提供三種葡萄酒建議。這道菜以西紅柿為主料，並且有點辣。',
  starterCompareQuery7: '為我提供 UN 的最新焦點的概要',
  starterCompareQuery8: '創建一個表格，用來比較出人意料的普利策獎獲得者及其原因',
  starterCompareQuery9: '用孩子能夠理解的方式介紹 Internet 的運作原理',
  starterCompareQuery10: '將“詩歌簡介”這首詩翻譯為法語，並用英語簡要解釋任何損失的含義',
  notificationMaxTurnsAndOpenEdge: '你已達到對話限制。若要繼續聊天，',
  notificationMaxTurnsAndOpenEdgeCta: '在 Microsoft Edge 中打開',
  actionBarPromptGuideToolTip: '提示指南',
  actionBarAttachButtonToolTip: '附加',
<<<<<<< HEAD
  actionBarLongPlaceholder: '詢問我任何內容或鍵入/新增人員、文件等'
=======
  promptLibraryButtonLabel: '查看提示',
  actionBarLongPlaceholder: '询问我任何内容或键入/添加人员、文件等',
  actionBarNotebookPlaceholder: '你有什么想法?编写与 AI 协作的详细提示。使用 Shift+Enter 提交邮件。',
  thirdPartyBingChatAttribution: '由 AI 支持的必应提供的结果',
  thirdPartyRAIDisclaimer: '可能会出现意外和错误',
  thirdPartyPrivacyHyperlink: '隐私',
  thirdPartyTermsHyperlink: '条款',
  usePreciseLocation: '更新地点',
  basedOnLocation: '基于: {0}、{1}',
  basedOnYourLocation: '基于你的位置',
  locationFetchErrorMessage: '权限被拒',
  locationLearnMore: '(了解详细信息)'
>>>>>>> upstream/master
};
function parseQueryParamsFromQuery (n, t) {
  var u, f, e, o;
  t === void 0 && (t = !0);
  var r = [],
    s = n && n.length > 0 ? n.split('&') : [],
    h = s.length,
    i = null;
  for (u = 0; u < h; u++)
    (f = s[u]), (e = f.indexOf('=')), e > 0 && ((i = f.substr(0, e)), i.charAt(0) == '?' && (i = i.substr(1)), i && ((i = i.toLowerCase()), (r[i] = f.substr(e + 1))));
  return t && ((o = r.first), (r.first = null == o || o == '0' ? 1 : parseInt(o))), r;
}
function parseQueryParams () {
  var n = '';
  return (
    (n = typeof Bing != 'undefined' && Bing.Url && Bing.Location ? Bing.Url.getQueryString(Bing.Location.get()) : _w.location.search.substring(1)), parseQueryParamsFromQuery(n)
  );
}
function convertQueryParamsToUrlStr (n, t) {
  t === void 0 && (t = null);
  var i = t ? t : _w.location.pathname.replace(/^\/+/, '/');
  return i + '?' + queryParamsToString(n);
}
function queryParamsToString (n) {
  for (var e, o, r, u, s, f, t = [], i = 1; i < arguments.length; i++) t[i - 1] = arguments[i];
  if (((e = []), (u = t.length), u == 0)) for (s in n) n.hasOwnProperty(s) && (t.push(s), u++);
  for (f = 0; f < u; f++) (o = t[f]), (r = n[o]), (r || r === 0) && e.push(o + '=' + r);
  return e.join('&');
}
function getCurrentQuery () {
  if (!currentQuery) {
    var n = parseQueryParams();
    currentQuery = n.q;
  }
  return currentQuery;
}
function extractDomainFromUrl (n, t, i) {
  var r, u, f, e;
  return typeof n != 'string'
    ? null
    : ((r = n),
      (u = r.indexOf('://')),
      u >= 0 && !t && ((r = r.substr(u + 3)), (u = -1)),
      (u = u >= 0 ? u + 3 : 0),
      (f = r.indexOf(':', u)),
      f >= 0 && (r = r.substr(0, f)),
      (f = r.indexOf('/', u)),
      f >= 0 && (r = r.substr(0, f)),
      (e = i ? r.indexOf('www.') : -1),
      e >= 0 && (r = r.substr(u + 4)),
      r);
}
function addCommonPersistedParams (n) {
  var i = parseQueryParams(),
    t = queryParamsToString(
      i,
      'atlahostname',
      'cdghostname',
      'thhostname',
      'testhooks',
      'adlt',
      'akamaithumb',
      'safesearch',
      'perf',
      'mockimages',
      'mobile',
      'anid',
      'isuserauth',
      'uncrunched',
      'clientid',
      'currentdate',
      'iss'
    ),
    r = n.indexOf('?') === -1 ? '?' : '&';
  return (t = t.length > 0 ? r + t : ''), n + t;
}
var currentQuery = null;
var fab_config = {
  fabStyle: 1,
  fabSbAction: 'FocusSearchBox',
  fabSbActionHover: 'None',
  fabSbActionData: 'None',
  fabTooltip: '',
  micFabAlwaysVisible: false,
  fabClickNoAS: false,
  FabAddSuggestions: false,
  DisableAlsoTryWhenHasPoleRS: false,
};
sj_be(
  _w,
  'click',
  function () {
    _G.UIWP = true;
  },
  1
);

// 設置未登錄用戶的 codexMUIDUser 為 true
const User_UCookieValue = CookieGet('_U')
if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
  _w['_sydConvConfig']['codexMUIDUser'] = true
}

const customChatNum = UserStoreGet('customChatNum')
if (customChatNum != 0) {
  if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
    _w['_sydConvConfig']['maxTurnsPerConversationMuidUser'] = customChatNum
  } else {
    _w['_sydConvConfig']['maxTurnsPerConversation'] = customChatNum
  }
}


if (UserStoreGet('enterpriseEnable')) {
  _w['_sydConvConfig']['disableWelcomeScreen'] = false
  _w['_sydConvConfig']['enableWelcomeScreenV2'] = false
  _w['_sydConvConfig']['enableTelemetryPrivacy'] = true
  _w['_sydConvConfig']['isMSAAuthenticated'] = false
  _w['_sydConvConfig']['isAccountLinkedWithActiveAAD'] = true
  _w['_sydConvConfig']['extraBceOptions'] = 'bcechat'
  _w['_sydConvConfig']['isBingChatForEnterprise'] = true
  _w['_sydConvConfig']['enableMessagePrivacy'] = true
  _w['_sydConvConfig']['PLoadIID'] = 'SERP.5833'
  _w['_sydConvTranslation']['warmWelcomeTitle'] = 'Mr.🆖 AI English Tutor'
  _w['_sydConvTranslation']['welcomeSubtitleText'] = '由Bing AI驅動的人工智能英語學習利器'
  _w['_sydConvTranslation']['inputRaiLabel'] = 'Mr.🆖 提提你：誠信學習、堅拒抄襲！'
}
