/* eslint-disable */
_w["_sydBaseSpecifierPrefix"] = "rms-answers-SharedStaticAssets-";
_w['_sydPayWallConfig'] = {
  loadSydneyConvResWithPayWall: false,
  useSydneyPayWall: false,
};
_w['_sydConvConfig'] = {
  enableBackgroundFix: true,
  usePill: true,
  enableSydTigerAns: true,
  tigerEnhancedPromptTemplate: 'Search for {0}. Impress me with a great response that helps me complete my most likely intent while showing the smartness, depth, and beauty (bolding, tables, and citations) you can produce. Satisfy my intent as early as possible in the response.',
  // 禁止滑出
  enableScrollOut: false,
  enableSydContext: true,
  sydOptionSets: 'logprobsc,bof108t525,log2sph,iwusrprmpt,iyjbexp,loccnt,dv3suggtrim',
  voiceSrOptions: 'cdxsrin',
  sydBalExtraOpts: 'saharagenconv5',
  sydCrtExtraOpts: 'clgalileo,gencontentv3',
  sydPrcExtraOpts: 'clgalileo,gencontentv3',
  sydIDs: 'arankr_1_9_9,926buffall,tts3cf,919disqbmetric,kcshower,kcshwrglss,kcusethumb,abv2bridgecf,creatordev,lessttscf,suppsm140-c,scpbfmob,sydtranslpre,kcmessfilcf,713logprobsc,926bof108t525,806log2sph,1004usrprmpt,927uprofasys0,0908loccnt,919vidsnips0,829suggtrim,917fluxvs0',
  sydBaseUrl: location.origin,
  isBingChatForEnterprise: false,
  isFeedbackEnabled: true,
  isSharingDiagnosticsEnabled: true,
  enable1JsSydneyToken: true,
  augloopEndpoint: 'https://augloop.office.com',
  enableProdEditorEndpoint: true,
  ciqReleaseAudienceGroup: 'Production',
  enableDeterminateProgressBar: true,
  sapphireArticleContentAPI: 'https://assets.msn.com/content/view/v2/Detail',
  sapphireSydneyQualificationAPI: '/edgesvc/postaj/sydneyqualification',
  sapphireSydneyZeroturnAPI: '/edgesvc/postaj/sydneyzeroturn',
  sapphireSydneyTruncationAPI: '/edgesvc/postaj/sydneytruncationswithcontext',
  enableSydPreloadAudioTTS: true,
  enableSydneyShareLink: true,
  country: 'United States',
  countryConfidence: 8,
  state: 'California',
  city: 'Los Angeles',
  cityConfidence: 0,
  zip: '90012',
  timezoneoffset: '8',
  lat: '78.4156',
  long: '-101.4458',
  language: 'Chinese (China)',
  userMailId: '123456@hotmail.com',
  username: 'Harry-zklcdc',
  userIpAddress: CookieGet('BingAI_Rand_IP'),
  isMSAAuthenticated: true,
  moveOnlySydXAnswers: true,
  enableSydX1T: true,
  enableSydTestCache: false,
  enableSydCarousel: true,
  traceId: randomLowercaseString(32),
  extraEdgeOptions: 'eredirecturl',
  enableSydMic: true,
  enableSydShare: true,
  enableSydCookLoc: true,
  enableSQMsg: true,
  addDv3Opt: true,
  enableErrorTelemetry: true,
  checkCreatorAnsFor1T: true,
  enableAnsCardSuffix: true,
  isAdultUser: true,
  enableSpeechExperimentalFeatures: true,
  enableSydAjaxReset: true,
  enableSydCLOC: true,
  enableCdxFeats: true,
  enableShareModalDialog: true,
  enableFdbkFinalized: true,
  enableDM: true,
  enableSydImageCreate: true,
  enableToneCook: true,
  toneDefault: 'Creative',
  balTone: 'galileo',
  crtTone: 'h3imaginative',
  prcTone: 'h3precise',
  enableSimpleVoiceInput: true,
  enableSpeechDictationMode: true,
  enableSpeechFateTTSStop: true,
  enableSpeechErrorHandling: true,
  enableSpeechTTSLatencyLogging: true,
  enableSpeechIconDarkTheme: true,
  enableSpeechAriaLabel: true,
  enableBalDefault: true,
  enableNewTopicAutoExpand: true,
  enableTelemetryPrivacy: false,
  isAccountLinkedWithActiveAAD: false,
  enableThreadsAADMSASwitch: true,
  enableMaxTurnsPerConversation: true,
  // 設置已登錄賬號的聊天對話次數
  maxTurnsPerConversation: 30,
  // 設置未登錄賬號的聊天對話次數
  maxTurnsPerConversationMuidUser: 10,
  maxMessageLength: 4000,
 
  enableTonePerf: true,
  enableSinglePerfEventPerMessage: true,
  enableAdSlugsMobile: true,
  enableUnauthRedir: true,
  enableVersionedApiCalls: true,
  enableFeedbackClientSideScreenshot: true,
  enableAddMobileTagToCibOnShowConv: true,
  enableStreamSyntheticTextResponses: true,
  enableStreamSyntheticTextResponsesForAllTones: true,
  syntheticStreamSpeed: 55,
  enableMobileShareAnchorBottom: true,
  enableShareConversation: true,
  enableGetConversationAPIWithSNRProxy: true,
  enableGetSharedMessagesAPIWithSNRProxy: true,
  enableShowShareButtonWithSecurityCheck: true,
  enableServerLogMerging: true,
  enableAutoRecoverFromInvalidSession: true,
  enableAutoRecoverFromInvalidSessionForFirstTurn: true,
  enableCodeCopy: true,
  enableCodeBar: true,
  enableInlineFeedback: true,
  enableInlineFeedbackV21: true,
  enableSerpFeedback: true,
  enablePersistentInputText: true,
  enableActionBarIMEFix: true,
  enableGhostTrailingSpaceByLanguage: true,
  shareLoadingUI: true,
  enableFeedbackInstrumentation: true,
  enableSydneySapphireUpsellMessageActions: true,
  sydneyContinueOnPhoneShortenQRCodeUrl: 'https://bingapp.microsoft.com/bing?style=newbing\u0026adjust=euhmno2_oy62nz1',
  enableSetToneFromUrl: true,
  convBackBtn: true,
  enableSetConvQueryFlag: true,
  enableSearchQueryForInlineAds: true,
  enableFixForInlineAdsSQ: true,
  codexPartnerScenario: 'SERP',
  enableMessageExport: true,
  enableFlatActionBar: true,
  enableAutosuggestMetrics: true,
  enableFixCodeXAsBug: true,
  enableThreads: false,
  enableSkipContentOriginCheck: true,
  enableMobileOneClickShareV2: true,
  enableScreenshotIgnoreOnCibSerp: true,
  enableStandaloneUtility: true,
  enableThreadShareLandingPage: true,
  enableShareThreadWithNoCache: true,
  enableShareCurrentThreadMessagesfromAPI: true,
  enablePreserveTextFormat: true,
  disable2TSearchHistory: true,
  enableSydBeacon: true,
  enableVisualSearch: true,
  visualSearchSubscriptionId: 'Bing.Chat.Multimodal',
  suppressPoleRSWhenEnableSydCarousel: true,
  disablePassBotGreetingInContext: true,
  enableThreadContextMenu: true,
  enableCloudflareCaptcha: true,
  enableResizeObserverWithAnimationFrame: true,
  enableStartPromotion: true,
  enableKnowledgeCardImage: true,
  enableMobileKnowledgeCardOverlay: true,
  enableCopyButtonInstrumented: true,
  enableMessageExportWithPlainText: true,
  enableMessageExportOnlineWord: true,
  enableThreadExportOnlineWord: true,
  enableMessageExportV2: true,
  enableDirectlyOpenExportOnlineLink: true,
  enableLoginHintForSSO: true,
  enableLimitToMsaOnlineExport: true,
  enableLimitToAadOnlineExport: true,
  enableTonePreview: true,
  enableMSAuth1stPartyApp: true,
  enableCopyHtml: true,
  enableGetChats: true,
  enableExportDocxWithFormat: true,
  enableThreadSync: true,
  codexTableVersion: true,
  disableWelcomeScreen: false,
  enableWelcomeScreenV2: false,
  enableBICHistory: true,
  enableRenderCardRequestIMSearchParams: true,
  typingIndicatorAnimationDuration: 1000,
  enableMessagePrivacy: false,
  enableOnProcessingStartEvent: true,
  enableOnProcessingCompleteEvent: true,
  enableTypewriter: true,
  enableUserMessageCopy: true,
  enableDeferredImageCreatorCard: true,
  enableUserIpAddress: true,
  enableActionBarV2: true,
  enableKatexScroll: true,
  padding2TMobile: 80,
  enablePageHeaderOverlapClamping: true,
  enableUpdateUserMessageId: true,
  enableMobileFirstClickShare: true,
  personalizationInlineConsentTurn: false,
  enableShareInThreadsHeader: true,
  enableDeleteSingleConversationMemory: true,
  threadsAutoSaveOptionset: 'autosave',
  enableOneDs: true,
  codexOptionsSetsList: [{
    value: 'iyxapbing'
  },
  {
    value: 'iycapbing'
  }],
  autoHideConvInterval: 3600000,
  PLoadIID: 'SERP.5870'
};
_w['_sydThreads'] = {
  threads: [],
};
_w['_sydConvTranslation'] = {
  actionBarPlaceholder: '問任何問題...（按 [ / ] 鍵觸發提示詞）',
  actionBarAriaLabel: '詢問必應',
  actionBarComposeButton: '新主題',
  actionBarNewChatButtonDesktop: '開始新聊天',
  actionBarNewChatButtonMobile: '新建聊天',
  actionBarOngoingConvPlaceholder: '鍵入消息',
  attachmentLoading: '正在加載附件',
  notiUpdateBrowser: '很抱歉，不支持此版本的瀏覽器。請將瀏覽器更新到最新版本以繼續。',
  bufferMessage1: '我正在使用它，請稍候',
  bufferMessage2: '請稍等',
  bufferMessage3: '花點時間思考...',
  captchaTitle: '驗証身份',
  captchaDescription: '若要繼續，請在下圖中輸入字符。',
  captchaPlaceholder: '輸入字符...',
  captchaPlaceholderError: '抱歉，請重試。',
  next: '下一步',
  cancel: '取消',
  feedbackAccessed: '訪問時間',
  feedbackSource: '源: 與必應的對話，',
  feedbackShareConversationQuery: '什麼是新版必應?',
  feedbackThanksMessageV2: '感謝你的反饋。請重新開始或刷新頁面。',
  messageLearnMore: '了解詳細信息:',
  messageReference: '參考',
  messageReferences: '引用',
  messagePrivacyLabel: '你的個人和公司數據在此聊天中受到保護',
  inputRaiLabel: '',
  letsChat: '我們聊天吧',
  pause: '暫停',
  play: '開始游戲',
  speechFailedRecognitionError: '抱歉，我無法收聽你的聲音，因為語音服務器已關閉，請稍後再試。',
  speechListening: '我聽著呢...',
  speechLoading: '正在等待音頻...',
  speechMediaNotReachableError: '很抱歉，我無法收聽你的聲音，因為你沒有可用的麥克風。',
  speechNoPermissionError: '你需要啟用麥克風，我才能聽到你的聲音。',
  speechAudioPlaybackError: '出錯了。',
  startOver: '重新開始',
  stop: '停止',
  welcomeContainerFAQs: '常見問題解答',
  welcomeContainerPrivacyStatement: '隱私',
  welcomeContainerUseTerms: '條款',
  welcomeContainerLearnMore: '了解更多',
  welcomeMessageItemContent1: 'Do a grammar check on the text I provide. Highlight the revised words for me.',
  welcomeMessageItemContent2: 'Give me 5 different versions of the text I provide.',
  welcomeMessageItemContent3: 'Randomly generate a 15-item vocabulary list from Oxford 3000, beginning with different letters, with the order of the entries in the list randomized, in the format "**English word** [繁體中文定義] <word class symbol>: example sentence 例句中文翻譯".',
  welcomeMessageItemTitle1: '🙌 檢查英語語法',
  welcomeMessageItemTitle2: '🎨 獲取改寫建議',
  welcomeMessageItemTitle3: '🧐 生成英語詞彙表',
  welcomeMessageItemLabel4: '更多創意中的新增功能：',
  warmWelcomeTitle: 'Mr.🆖 AI English Tutor',
  warmWelcomeTitleLine2: '',
  warmWelcomeAriaLabel: 'Mr.🆖 AI English Tutor',
  welcomeSubtitleText: '由Bing AI驅動的人工智能英語學習利器',
  workToggleDescription: '以及你的結果包括哪些內容',
  feedbackFirstMessage: '非常抱歉沒有幫助到你。是否可以詳細說明你不喜歡的方面?',
  feedbackPromptMessage: '感謝提醒。請提供反饋，以便必應團隊可以查看。',
  feedbackPromptGiveFeedback: '提供反饋',
  feedbackPromptGiveFeedbackAriaLabel: '提供反饋',
  feedbackPromptReportAConcern: '報告問題',
  feedbackPromptPositive: '很高興你喜歡這個答案！',
  feedbackFormTitleText: '為什麼這不起作用？',
  feedbackFormInputDefaultText: '在此處添加更多詳細信息。為了幫助保護你的隱私，請不要填入你的姓名或電子郵件地址等個人信息。',
  feedbackFormLegalText: '是否有法律或政策問題？',
  feedbackFormReportAConcern: '報告問題',
  feedbackFormNotificationTitleText: '反饋已提交',
  feedbackFormNotificationBodyText: '感謝你幫助必應改進！',
  feedbackFormThanksMessage: '感謝你提供的反饋!',
  feedbackFormReturnToChatMessage: '返回到聊天',
  serpFeedbackFormTitleText: '請幫助我們改進體驗',
  serpFeedbackFormInputDefaultText: '在此處輸入反饋。為了幫助保護你的隱私，請不要填入你的姓名或電子郵件地址等個人信息。',
  serpFeedbackFormScreenshot: '包括此屏幕截圖',
  serpFeedbackFormRadioLike: '贊',
  serpFeedbackFormRadioDislike: '踩',
  serpFeedbackFormRadioConnectionIssues: '連接問題',
  serpFeedbackFormRadioSlowResponses: '回應緩慢',
  serpFeedbackFormRadioOther: '其他',
  feedbackFormUnderstandDataSharedText: '詳細了解作為診斷數據共享的內容',
  feedbackFormUserConsentText: '將提示共享到 Copilot、從 Copilot 收到的回應，以及此交互的診斷數據?',
  feedbackFormUserConsentYesText: '是',
  feedbackFormUserConsentNoText: '否',
  feedbackFormPrivacyStatement: '隱私聲明',
  feedbackFormPrivacyText: '按“提交”後，你的反饋將用於改進 Microsoft 產品和服務。組織的 IT 管理員將能夠查看和管理反饋數據。',
  compliantPositiveFeedbackFormTitleText: '向 Microsoft 提交反饋',
  compliantPositiveFeedbackQuestionText: '你喜歡哪些方面?',
  compliantPositiveFeedbackDefaultText: '請不要提供任何個人信息。',
  compliantNegativeFeedbackFormTitleText: '向 Microsoft 發送詳細反饋',
  compliantNegativeFeedbackCategoryText: '該內容是',
  compliantNegativeFeedbackQuestionText: '出了什麼問題?',
  compliantFeedbackThanksText: '感謝你提交關於 {0} 的反饋!',
  compliantFeedbackCategoryInaccurate: '不準確',
  compliantFeedbackCategoryOffensive: '冒犯性或不適宜',
  compliantFeedbackCategoryOther: '其他',
  submit: '提交',
  explore: '瀏覽',
  exploreMore: '瀏覽更多',
  metaInternalSearchQuery: '正在搜索: `{0}`',
  metaInternalLoaderMessage: '正在為你生成答案...',
  metaInternalImageLoaderMessage: '分析圖像: 隱私模糊會隱藏聊天中的人臉',
  compliantMetaInternalLoaderMessage: '從 {0} 生成安全答案',
  messageSharedContent: '共享內容',
  clickToView: '單擊以查看',
  more: '更多',
  expand: '展開',
  welcomeTertiaryTitleText: '使用 AI 的強大功能從 Web 中查找答案、創建書面內容等。',
  actionBarTextInputAriaLabel: '詢問必應',
  seeMore: '查看更多',
  seeLess: '查看更少',
  raiSuggestions: '這是什麼?',
  actionBarFileUploadButtonAriaLabel: '在文件中搜索',
  actionBarStopStreamingAriaLabel: '停止流式傳輸',
  actionBarTextInputModeButtonAriaLabel: '使用鍵盤',
  actionBarSpeechInputModeButtonAriaLabel: '使用麥克風',
  actionBarVisualSearchButtonTooltip: '添加圖像',
  actionBarVisualSearchButtonAriaLabel: '添加要搜索的圖像',
  actionBarVisualSearchCoachMarkTitle: '帶圖像的新必應',
  actionBarVisualSearchCoachMarkDescription: '現在你可以使用圖像與必應聊天！',
  actionBarVisualSearchCoachMarkImgAlt: '視覺搜索工具提示圖像',
  actionBarSubmitButtonAriaLabel: '提交',
  actionBarCancelSpeechInputButtonAriaLabel: '取消語音輸入/讀出',
  actionBarEditModeButtonAriaLabel: '固定',
  actionBarSpeechBtnStartListeningAriaLabel: '使用麥克風',
  actionBarSpeechBtnStopListeningAriaLabel: '停止偵聽',
  actionBarSpeechBtnStopReadoutAriaLabel: '停止讀出',
  feedbackLikeButtonAriaLabel: '點贊',
  feedbackDislikeButtonAriaLabel: '不喜歡',
  feedbackOffensiveButtonAriaLabel: '標記為冒犯性',
  feedbackCopyButtonAriaLabel: '複製',
  feedbackShareButtonAriaLabel: '共享',
  messageSentAriaLabelPrefix: '已發送電子郵件',
  messageReceivedAriaLabelPrefix: '已收到消息',
  messageReportedOffensiveAndRemoved: '已刪除此消息，因為它已被舉報待審查。',
  messageAttributionsCollapseBtnAriaLabel: '折疊',
  newTopicGreet1: '謝謝你! 知道你什麼時候准備好繼續前進總是很有幫助的。我現在能為你回答什麼問題?',
  newTopicGreet2: '重新開始總是很棒。問我任何問題!',
  newTopicGreet3: '當然，我很樂意重新開始。我現在可以為你提供哪些幫助?',
  newTopicGreet4: '當然，我已准備好進行新的挑戰。我現在可以為你做什麼?',
  newTopicGreet5: '很好，讓我們來更改主題。你在想什麼?',
  newTopicGreet6: '不用擔心，我很高興嘗試一些新內容。我現在可以為你回答什麼問題?',
  newTopicGreet7: '好的，我准備好了！感謝重置。我們應該了解哪些內容？',
  newTopicGreet8: '感謝刷新！你有新的話題嗎？',
  newTopicGreet9: '明白了，讓我們重新開始。接下來應該討論什麼？',
  newTopicGreet10: '下一步！我可以為你做什麼？',
  newTopicGreet11: '好的，我已准備好新話題。我們應該一起了解哪些內容？',
  newTopicGreet12: '明白了，請繼續！感謝告訴我。我能提供什麼幫助？',
  newTopicSugg1: '教我一個新單詞',
  newTopicSugg2: '如何設定可實現的目標?',
  newTopicSugg3: '教我有關登月的信息',
  newTopicSugg4: '世界上最小的哺乳動物是什麼?',
  newTopicSugg5: '最深的海洋是哪個?',
  newTopicSugg6: '一年有多少小時?',
  newTopicSugg7: '我想學習一項新技能',
  newTopicSugg8: '讓我大笑',
  newTopicSugg9: '有什麼新聞?',
  newTopicSugg10: '給我看鼓舞人心的名言',
  newTopicSugg11: '給我說個笑話',
  newTopicSugg12: '我需要有關家庭作業的幫助',
  newTopicSugg13: '尋找非虛構作品',
  newTopicSugg14: '激勵我!',
  newTopicSugg15: '向我顯示食譜',
  newTopicSugg16: '如何創建預算?',
  newTopicSugg17: '教我一個新單詞',
  newTopicSugg18: '天氣如何?',
  newTopicSugg19: '我想學習一項新技能',
  newTopicSugg20: '宇宙是如何開始的?',
  newTopicSugg21: '為什麼人類需要睡眠?',
  newTopicSugg22: '如何制作蛋糕?',
  newTopicSugg23: '火烈鳥為何為粉色?',
  newTopicSugg24: '全息影像的工作原理是什麼?',
  newTopicSugg25: '金字塔是如何建成的?',
  newUserGreet: '歡迎！我是必應，我可以使用 AI 完成更多工作，例如幫助你找到完美的禮物、了解海洋或發現新音樂。告訴我你想要了解的內容！',
  newUserSugg1: '給我說個笑話',
  newUserSugg2: '玩小游戲',
  newUserSugg3: '給我講一個謎語',
  repeatUserGreet: '很高興你回來了！無論你想說什麼，我都持開放態度。我能為你做什麼？',
  repeatUserSugg1: '有什麼最新資訊',
  repeatUserSugg2: '向我展示一首詩',
  repeatUserSugg3: '給我說個笑話',
  creativeGreet: '讓我們發揮創意吧！你是否在考慮某個主題，還是即興發揮？',
  balancedGreet: '聽起來不錯，我們可以在趣事和事實中尋找平衡。如何提供幫助？',
  preciseGreet: '感謝聊天。今天我能幫你嗎？',
  creativeSugg1: '告訴我一個奇怪的事實',
  creativeSugg2: '告訴我的星座',
  creativeSugg3: '給我一個你想問的問題',
  balancedSugg1: '寫一首關於爆米花的詩',
  balancedSugg2: '蜜蜂如何釀蜜？',
  balancedSugg3: '我需要幫助制定計劃',
  preciseSugg1: '誰發明語言？',
  preciseSugg2: '我需要幫助做研究',
  preciseSugg3: '是什麼讓地球旋轉？',
  close: '關閉',
  newTopicPrompt: '通過新主題，可以開始與必應就任何主題進行全新對話',
  typingIndicatorStopRespondingAriaLabel: '停止回應',
  loading: '正在加載',
  canceling: '正在取消',
  welcomeLearnSegment0: '必應由 AI 提供支持，因此可能出現意外和錯誤。請確保核對事實，並',
  welcomeLearnSegment1: '讓我們一起學習。必應由 AI 提供支持，因此可能出現意外和錯誤。請確保核對事實，並 ',
  welcomeLearnSegment2: '共享反饋 ',
  welcomeLearnSegment3: '以便我們可以學習和改進!',
  welcomeLearnMessage: '讓我們一起學習。必應由可以理解並生成文本和圖像的 AI 提供支持，因此可能出現意外和錯誤。請確保核對事實，並 {0} 以便我們可以學習和改進！',
  welcomeLearnMessage2: '必應聊天會處理你在 Windows Copilot 中輸入的字詞，以生成 AI 驅動的響應，並改善你在 Windows 中的體驗。',
  welcomeLearnFeedbackSubstitute: '共享反饋',
  adsDisclaimer: '廣告不是基於工作區標識或聊天歷史記錄的目標。{0}。',
  adsDisclaimerMobileTitle: null,
  adsDisclaimerLearnMoreLink: '了解更多',
  actionBarSuspendConvPlaceHolder: '已為挂起的帳戶禁用消息傳遞',
  actionBarNewlineTooltip: '使用 Shift+Enter 為較長的消息創建換行符',
  notiReConnect: '出錯了。',
  notiChatEnd: '聊天主題已結束。',
  notiRestartChat: '在 {0} 小時內開始新主題',
  notificationAttemptingToReconnect: '正在嘗試重新連接...',
  notificationProcessing: '正在嘗試連接，請稍候',
  notificationLostConnection: '很抱歉，你的連接似乎已斷開。',
  notificationLostConnectionCta: '是否要嘗試重新連接？',
  sydneySapphireCopyToClipboardText: '已複製到剪貼板。',
  sydneySapphireUpsellContent: '現在就獲取使用新 AI 驅動的必應應用程序吧!',
  sydneySapphireWelcomeText: '歡迎回來! 下面是此頁面的一些內容。',
  sydneySapphireConsentTitleText: '使用新必應提升瀏覽',
  sydneySapphireConsentMessageText: '允許 Microsoft 訪問你的瀏覽器 Web 內容，以便使用 AI 生成的摘要和新必應的熱點功能更好地個性化你的體驗。了解更多信息',
  sydneySapphireConsentConfirmText: '確認',
  sydneySapphireConsentDenyText: '拒絕',
  sydneySapphireSummarizeSuggestionShip: '匯總',
  sydneySapphireExplainSuggestionShip: '解釋',
  sydneySapphireKeyTakeawaysSuggestionShip: '關鍵要點',
  sydneySapphireAskMeaningSuggestionChip: 'What does that mean?',
  sydneySapphireRelevantInformationSuggestionChip: 'Give me relevant information about this',
  sydneySapphireOverviewSuggestionChip: 'Could you provide a brief overview?',
  sydneySapphireGenerateSummaryMessage: '生成此頁面的摘要',
  sydneySapphireContextGreet: 'It looks like you asked about {0}. What do you want to know about this?',
  sydneySapphireGPT4Greet: '讓我們通過 GPT-4 🎉獲得創意。在發揮創意的同時，回應速度可能會變慢。你是否在考慮某個主題，還是應該為其建立分支?',
  typingIndicatorStopStreamingAriaLabel: '停止流式傳輸',
  sydneyCarouselCollapse: '折疊',
  sydneyCarouselTitle: '最近的聊天主題',
  messageActionsCopy: '複製',
  messageActionsCopying: '正在複製',
  messageActionsCopied: '已複製',
  messageActionsCopyError: '錯誤',
  messageActionsReport: '報告',
  tooltipPositive: '點贊',
  tooltipNegative: '不喜歡',
  tooltipShare: '共享',
  tooltipMore: '更多',
  tooltipSendToPhone: '在手機上繼續',
  codeDisclaimer: '此代碼由 AI 生成。仔細查看和使用。有關詳細信息，請{0}。',
  codeDisclaimerLinkLabel: '訪問我們的常見問題解答',
  exportTitle: '導出',
  exportTextTitle: '下載為文本(.txt)',
  exportPdfTitle: '以 PDF (.pdf)格式下載',
  exportWordTitle: '以 Word (.docx)格式下載',
  exportWordOnlineTitle: '導出到 Word Web 應用',
  exportExcelTitle: '以 Excel (.xlsx)格式下載',
  exportExcelOnlineTitle: '導出到 Excel Web 應用',
  exportToastViewButtonLabel: '查看',
  exportSuccessToastTitle: '已導出文件。某些格式和圖像可能無法導出。',
  exportErrorToastTitle: '導出失敗',
  exportLoadingToastTitle: '正在導出...',
  exportedFileUserTitle: '用戶',
  exportedFileBotTitle: '必應',
  feedbackExportButtonAriaLabel: '導出',
  feedbackExportPdfButtonAriaLabel: 'PDF',
  feedbackExportTextButtonAriaLabel: 'Text',
  feedbackExportWordButtonAriaLabel: 'Word',
  tooltipExport: '導出',
  messageActionsExportPdf: 'PDF',
  messageActionsExportText: 'Text',
  messageActionsExportWord: 'Word',
  exportOnlineWordButtonLabel: '聯機 Word',
  exportLocalWordButtonLabel: '下載',
  exportTableToExcelButtonTooltip: '在瀏覽器中打開',
  mobileUpsellMessage1: '掃描此 QR 碼以在移動必應應用上繼續此對話',
  mobileUpsellTitle1: '在手機上繼續',
  visualSearchMobileUpsellLabel: 'Use Bing app on phone',
  mobileUpsellTitle2: 'Use Bing app to take photo',
  mobileUpsellMessage2: 'Scan QR code to take this photo with the Bing app on your mobile device',
  sydneySapphireUpsellConsentTitle: '是否繼續從桌面聊天?',
  sydneySapphireUpsellConsentMessage: '你在其他設備上有一個活動的必應聊天。是否要繼續此對話?',
  sydneySapphireUpsellConsentConfirm: '是',
  sydneySapphireUpsellConsentDeny: '不，謝謝',
  actionBarAutoSuggestTab: 'Tab',
  actionBarAutoSuggestTap: '點擊',
  actionBarKeyboardHint: '輸入',
  feedbackShareAnswer: '查看此必應答案',
  feedbackShareGenerated: '查看我使用必應生成的內容',
  feedbackShareTitleFormat: '{0} | {1}',
  feedbackShowTonesButtonAriaLabel: '顯示所有音調',
  feedbackHideTonesButtonAriaLabel: '隱藏所有色調',
  feedbackHidePreciseToneButtonAriaLabel: '隱藏精確',
  feedbackShareErrorToast: '共享失敗。',
  serpfeedback: '反饋',
  shareConversation: '共享整個對話',
  speechAuthenticationError: '身份驗証失敗。請稍後重試。',
  speechUnknownError: '出錯了。',
  refresh: '刷新',
  feedbackShareContent: '下面是我使用新的必應（全球首個 AI支持的應答引擎）生成的答案。單擊可查看完整答案，然後請你也來試一試。',
  fileUploadFlyoutInputboxAriaLabel: '粘貼網頁 URL',
  fileUploadFlyoutTitle: '添加文本文件',
  fileUploadFlyoutUploadButtonLabel: '從此設備上傳',
  fileUploadGenericErrorMessage: '抱歉 - 上傳似乎失敗。請重試',
  preview: '預覽',
  toneSelectorDescription: '.',
  toneSelectorCreative: '有創造力',
  toneSelectorCreativeModifier: '更',
  toneSelectorBalanced: '平衡',
  toneSelectorBalancedModifier: '更',
  toneSelectorPrecise: '精確',
  toneSelectorPreciseModifier: '更',
  toneSelectorMoreCreative: '更\\r\\n有創造力',
  toneSelectorMoreBalanced: '更\\r\\n平衡',
  toneSelectorMorePrecise: '更\\r\\n精確',
  toneSelectorFaster: '更快',
  toneSelectorWithGPT4: '使用 GPT-4',
  notificationMaxTurnsPerDay: '很抱歉，你已達到可在 24 小時內發送到必應的郵件限制。請稍後回來查看!',
  notificationMaxTurnsPerConversation: '很抱歉，此對話已達到其限制。使用“掃除”按鈕清除此內容並進行更多聊天。',
  notificationMaxTurnsForMuidUsers: '你已達到今天的對話限制。',
  notificationMaxTurnsForInPrivateUsers: '你已達到 inPrivate 模式的會話限制。打開非 inPrivate 窗口以繼續聊天',
  notificationUnauthorizedMuidUsersCta: '登錄以繼續你的聊天。',
  notificationChatEnterMuidUsers: '登錄以提出更多問題並進行更長的對話。',
  muidUsersTermsCond1: '通過單擊“開始使用”，並繼續與必應交互，即表示你接受',
  muidUsersTermsCond1Inline: '通過繼續與必應交互，你將接受 ',
  muidUsersTermsCond2: '並確認你已查看',
  muidUsersPrivacyStatement: '隱私聲明',
  muidUsersTermsOfUse: '使用條款',
  muidUserGetStartedText: '開始使用',
  muidUserContinueText: '繼續',
  welcomeMobSugg1: '必應如何使用 AI?',
  welcomeMobSugg2: '必應還可以做什麼？',
  welcomeMobSugg3: '科技領域的最新消息是什麼？',
  of: '共',
  notificationResetConversation: '很抱歉，似乎出現錯誤。',
  notificationResetConversationCta: '讓我們重新開始吧。',
  toneSelectorCreativeTooltip: '清除對話並開始原創和富有想象力的聊天',
  toneSelectorBalancedTooltip: '清除對話並開始一個信息豐富且友好的聊天',
  toneSelectorPreciseTooltip: '清除對話並開始簡潔直截了當的聊天',
  toneSelectorSuppressedTooltip: '暫時不可用。請稍後再試!',
  notificationDisengaged: '也許該換個新話題了。',
  notificationDisengagedCta: '',
  notificationForbidden: '很抱歉，你似乎不再有權訪問此功能。請幾天後再次查看。',
  notificationTooManyRequests: '很抱歉，現在需求量非常大。請稍後重試。',
  notificationUnauthorized: '很抱歉，你似乎已注銷。',
  notificationUnauthorizedCta: '請重新登錄。',
  notificationMessageError: '上一條消息似乎已中斷。',
  notificationSharedTip: '此對話\u003cstrong\u003e“{0}”\u003c/strong\u003e已於 {1} 與你共享',
  mmAnswerPrompt1: '我總算給你找到了一些東西! 看一看。',
  mmAnswerPrompt2: '我終於找到了一些東西! 這是你要找的嗎?',
  mmAnswerPrompt3: '抱歉搞混了，我確實給你找到了一些東西。給你!',
  mmAnswerPrompt4: '嘿! 我確實找到了一些東西，這是你想要的嗎?',
  mmAnswerPrompt5: '看! 我找到了一些適合你的內容。',
  mmAnswerPrompt6: '等等，在這裡! 抱歉弄亂了，看一下吧。',
  mmAnswerPrompt7: '我找到你要的媒體了! 抱歉耽擱了。',
  signInCta: '登錄 ',
  signInDescription: ' 以提出更多問題並進行更長的對話',
  signInDescriptionInPrivate: '打開非 inPrivate 窗口，以便進行更長的對話或提出更多問題',
  copyCodeSuccessToastTitle: '已複製到剪貼板',
  copyCodeButtonTooltip: '複製',
  copyCodeButtonSuccessTooltip: '已複製',
  threadsSharedOnDate: '於 {0} 共享',
  threadsMore: '更多',
  threadsExportPanelTitle: '選擇格式',
  threadsExportPanelAriaLabel: '選擇',
  threadsAADMSARedirectConfirm: '切換用戶配置',
  threadsAADMSARedirectDescription: '正在使用 Microsoft 帳戶保存你的對話歷史記錄。下次使用個人帳戶登錄時，它將在此處顯示。',
  threadsCancel: '取消',
  threadsChatHistory: '聊天記錄',
  threadsConfirm: '確認',
  threadsDaysAgo: '{0} 天前',
  threadsDefaultChatName: '無標題的聊天',
  threadsDelete: '刪除',
  threadsDescription: 'AI 支持的助手必應現可自動保存聊天。你可以從任何設備、桌面或移動設備訪問聊天，無縫地繼續。',
  threadsDescriptionNote: '請注意，除非專門保存，否則所有聊天將在 90 天內自動刪除。',
  threadsEdit: '重命名',
  threadsLoad: '加載聊天',
  threadsMinimizeRecent: '最小化最近的聊天',
  threadsMinimizeSaved: '最小化保存的聊天',
  threadsPreview: '預覽',
  threadsPreviewText: '跳回最近聊天',
  threadsRecentTitle: '最近的活動',
  threadsRecentTitleShort: '最近使用',
  threadsSavedTitle: '已保存',
  threadsSeeAllRecent: '查看所有最近的聊天',
  threadsSeeAllSaved: '查看所有保存的聊天',
  threadsTitle: '聊天',
  threadsTitleForFlux: '菜單',
  threadsYesterday: '昨天',
  threads2TLastAccessed: '上次應答時間',
  threads2TInfoChanged: '此信息可能已更改，因為',
  threads2TArchivedText: '屏幕截圖',
  threads2TReloadDescription: '單擊“重新加載”以顯示來自 Web 的最新信息',
  threads2TFailedSearch: '請參閱最新 Bing.com',
  threads2TReload: '搜索 Bing.com',
  injectedActionCardTitle: '就此頁面進行聊天?',
  injectedActionCardNewTopicTitle: '開始有關此頁面的新聊天?',
  injectedActionCardConfirm: '發送',
  injectedActionCardDeny: '忽略',
  webPageContextPrefix: '已訪問網站',
  useGPT4SwitchLabel: '使用 GPT-4',
  zeroInputSuggestionFallback1: 'Randomly generate a 15-item vocabulary list from Oxford 3000, beginning with different letters, with the order of the entries in the list randomized, in the format "**English word** [繁體中文定義] <word class symbol>: example sentence 例句中文翻譯".',
  zeroInputSuggestionFallback2: '對於一個預算有限的六口之家來說，會首選哪三款車型？',
  zeroInputSuggestionFallback3: '寫一個我的同事會覺得有趣的笑話',
  zeroInputSuggestionFallback4: 'Do a grammar check on the text I provide. Highlight the revised words for me.',
  zeroInputSuggestionFallback5: '撰寫關於魚和青蛙尋找愛的原創寓言故事',
  zeroInputSuggestionFallback6: 'Give me 5 different versions of the text I provide.',
  zeroInputSuggestionFallback7: '為具有諷刺風格的新社交媒體平台創建一個口號',
  zeroInputSuggestionCategory1: '生成英語詞彙表',
  zeroInputSuggestionCategory2: '比較',
  zeroInputSuggestionCategory3: '大笑',
  zeroInputSuggestionCategory4: '檢查英語語法',
  zeroInputSuggestionCategory5: '寫入',
  zeroInputSuggestionCategory6: '獲取改寫建議',
  zeroInputSuggestionCategory7: '創建',
  discoverMessageItemTitle: '📝 一起重寫文本',
  discoverMessageItemContent: '嘗試從頁面中選擇文本以查看我們可以一起執行的操作',
  pluginTitle: '插件',
  bookNowWithOpenTable: '立即使用 OpenTable 預訂',
  scrollLeft: '向左滾動',
  scrollRight: '向右滾動',
  personalizationConsentTitleText: '✨ 對了，你想要個性化的答案嗎?✨',
  personalizationConsentContentText1: '共享聊天歷史記錄時，必應會根據你和你的興趣定製回覆。',
  personalizationConsentContentText2: '。',
  personalizationConsentLearnMoreText: '了解有關個性化答案的詳細信息',
  personalizationConsentEnableText: '是的，我想要!',
  personalizationConsentAskAgainLaterText: '以後再說',
  personalizationConsentDisableText: '不，謝謝',
  personalizationConsentStatusPositiveText: '已啟用個性化。',
  personalizationConsentStatusNegativeText: '未啟用個性化。',
  personalizationConsentSettingsText1: '若要修改，請訪問',
  personalizationConsentSettingsLinkText: '必應聊天設置',
  personalizationConsentSettingsText2: '頁面',
  pluginEnabledPlugin: '已啟用',
  pluginEnabledNumber: '{0} / {1}',
  pluginStartNewTopic: '開始新主題',
  pluginToChangePlugin: '更改插件',
  pluginNotificationMaxExceeded: '已啟用的最大插件數',
  pluginNotificationExclusive: '{0} 與 {1} 太相似。請選擇一個',
  pluginTerms: '使用條款',
  pluginPrivacy: '隱私策略',
  pluginPanelFreTitle: '插件現在可用',
  pluginPanelFreTextLabel: '新建:',
  pluginPanelFreText: '打開插件，幫助你從喜歡的品牌中查找餐廳預訂、航班等。',
  pluginPanelFreDismiss: '忽略',
  pluginPanelAlertTitle: '插件在“平衡”模式下不可用',
  pluginPanelAlertCta: '重置對話 ',
  pluginPanelAlertSubtitle: '並使用“更多創意”或“更精確”對話樣式，然後重試。',
  pluginLimitationTitle: '將插件與必應 AI 配合使用',
  pluginLimitationMax: '最多為任意一個對話線程選擇 3 個插件。',
  pluginLimitationLock: '在選擇“新建主題”進行更改之前，插件會鎖定到對話中。',
  pluginShowMore: '展開',
  pluginPanelNolimit: '禁用 {0} 不會影響插件限制',
  threadsToggleExpansion: '切換擴展',
  threadsEnabledPlugins: '已啟用插件:',
  bingSearchDisabled: '必應**已禁用**。',
  bingSearchDisabledforMessage: '必應已禁用',
  activateSearch: '啟動新主題並激活搜索',
  visualSearchFlyoutTitle: '添加圖像',
  visualSearchGenericErrorMessage: '無法上傳該文件。請重試。',
  visualSearchUnsupportedFileMessage: '不支持此文件類型。選擇圖像文件，然後重試。',
  visualSearchInvalidUrlMessage: '抱歉 - 你提供的 URL 似乎無效。請重試',
  visualSearchFlyoutInputboxAriaLabel: '粘貼圖像或鏈接',
  visualSearchFlyoutTakePhotoButtonLabel: '拍照',
  visualSearchDragAndDropLabel: '將圖片拖至此處',
  visualSearchFlyoutUploadButtonLabel: '從此設備上傳',
  raiDisclaimerLabel: 'AI 生成的內容可能不正確',
  slimHeaderTitle: '查看 AI 支持的新必應的解答',
  starterPageTitle: '由Bing AI驅動的人工智能英語學習利器',
  starterDescription: '用你自己的語言與必應聊天。如果感到卡住，請選擇以下開場白之一，以觀察必應是如何運作的：',
  starterSubtitle1: '進行對話',
  starterSubtitle2: '釋放你的創造力',
  starterSubtitle3: '更智能地搜索',
  starterContent1: '像日常聊天一樣使用自然語句並詢問后續內容時，必應效果最佳',
  starterContent2: '無論是用圖像還是文字，必應可以通過讓你的願景變為現實來激發你的創造力',
  starterContent3: '與必應聊天是一種新搜索方式。讓必應匯總 Web 內容並提供答案',
  starterChatQuery1: '你認為其他行星上有生命嗎？地球的獨特之處是什麼？',
  starterChatQuery2: '如果我睡眠遇到問題，但隻在夏天發生，是怎麼回事？',
  starterChatQuery3: '我想開辟一個花園，但我對此一無所知。第一步需要做什麼？',
  starterChatQuery4: '你認為鱷魚或灰熊會在搏斗中獲勝嗎？',
  starterChatQuery5: '我最近讀了很多非虛構類書籍。你能幫我找到我喜歡的主題的虛構類版本嗎？',
  starterChatQuery6: '讓我們進行一次對話，其中你說的所有內容都是用表情符號編寫的。',
  starterChatQuery7: '我一直在考慮搬到一個新的地方。你認為我應該去哪兒？',
  starterChatQuery8: '我曾經寫過日記，但最近經常偷懶。我如何才能保持習慣？',
  starterChatQuery9: '你是否會像人類一樣做夢？你會夢到什麼？',
  starterChatQuery10: '是否可能同時發生地震、海嘯和火山噴發？',
  starterCreateQuery1: '我有一隻黑毛的小狗，除了肚子上的毛是白色的。請將它畫成卡通形象。',
  starterCreateQuery2: '為我的 3 歲的侄女寫一個睡前故事。她喜歡馬和魔法，而且我認為這個故事應該押韻”',
  starterCreateQuery3: '用一位高傲自大的教授的語氣撰寫一篇短文，來証明月亮比太陽更好',
  starterCreateQuery4: '用印象派風格畫一隻在冰山上晒太陽的北極熊。它還應該在喝檸檬水',
  starterCreateQuery5: '讓我們來創造一種顏色，並撰寫一個社交媒體帖子向全世界介紹它',
  starterCreateQuery6: '作為由 Christian Bale 扮演的蝙蝠俠，請告訴我如何騎著摩托車應對交通',
  starterCreateQuery7: '用一位在家釀酒並引發小型爆炸的爸爸的語氣，為一個新的啤酒品牌制作銷售宣傳',
  starterCreateQuery8: '為一家咖啡館設計一副海報，其中包含日落並充分利用空間',
  starterCreateQuery9: '畫一隻身為湖上躉船船長的長頸鹿',
  starterCreateQuery10: '為一篇有關女權主義文學歷史的論文撰寫簡介段落，並為我提供五個寫作提示以繼續',
  starterCompareQuery1: '為我找一份提拉米蘇的菜譜，為我制作一個購物清單，然后進行排列，以便我可以在商店中快速找到配料',
  starterCompareQuery2: '為我提供的今天的本地新聞匯報，不包括體育內容”',
  starterCompareQuery3: '用五個要點總結最新的 AI 研究，並得出接下來的發展趨勢的結論',
  starterCompareQuery4: '創建一個表格，用來按品牌、價格、安全功能和可能的附加設備比較最佳電動車',
  starterCompareQuery5: '這附近有兒童游樂場的最近的公園在哪裡？',
  starterCompareQuery6: '為我晚上要做的意大利菜提供三種葡萄酒建議。這道菜以西紅柿為主料，並且有點辣。',
  starterCompareQuery7: '為我提供 UN 的最新焦點的概要',
  starterCompareQuery8: '創建一個表格，用來比較出人意料的普利策獎獲得者及其原因',
  starterCompareQuery9: '用孩子能夠理解的方式介紹 Internet 的運作原理',
  starterCompareQuery10: '將“詩歌簡介”這首詩翻譯為法語，並用英語簡要解釋任何損失的含義',
  notificationMaxTurnsAndOpenEdge: '你已達到對話限制。若要繼續聊天，',
  notificationMaxTurnsAndOpenEdgeCta: '在 Microsoft Edge 中打開',
  actionBarPromptGuideToolTip: '提示指南',
  actionBarAttachButtonToolTip: '附加',
  actionBarLongPlaceholder: '詢問我任何內容或鍵入/添加人員、文件等'
};
function parseQueryParamsFromQuery (n, t) {
  var u, f, e, o;
  t === void 0 && (t = !0);
  var r = [],
    s = n && n.length > 0 ? n.split('&') : [],
    h = s.length,
    i = null;
  for (u = 0; u < h; u++)
    (f = s[u]), (e = f.indexOf('=')), e > 0 && ((i = f.substr(0, e)), i.charAt(0) == '?' && (i = i.substr(1)), i && ((i = i.toLowerCase()), (r[i] = f.substr(e + 1))));
  return t && ((o = r.first), (r.first = null == o || o == '0' ? 1 : parseInt(o))), r;
}
function parseQueryParams () {
  var n = '';
  return (
    (n = typeof Bing != 'undefined' && Bing.Url && Bing.Location ? Bing.Url.getQueryString(Bing.Location.get()) : _w.location.search.substring(1)), parseQueryParamsFromQuery(n)
  );
}
function convertQueryParamsToUrlStr (n, t) {
  t === void 0 && (t = null);
  var i = t ? t : _w.location.pathname.replace(/^\/+/, '/');
  return i + '?' + queryParamsToString(n);
}
function queryParamsToString (n) {
  for (var e, o, r, u, s, f, t = [], i = 1; i < arguments.length; i++) t[i - 1] = arguments[i];
  if (((e = []), (u = t.length), u == 0)) for (s in n) n.hasOwnProperty(s) && (t.push(s), u++);
  for (f = 0; f < u; f++) (o = t[f]), (r = n[o]), (r || r === 0) && e.push(o + '=' + r);
  return e.join('&');
}
function getCurrentQuery () {
  if (!currentQuery) {
    var n = parseQueryParams();
    currentQuery = n.q;
  }
  return currentQuery;
}
function extractDomainFromUrl (n, t, i) {
  var r, u, f, e;
  return typeof n != 'string'
    ? null
    : ((r = n),
      (u = r.indexOf('://')),
      u >= 0 && !t && ((r = r.substr(u + 3)), (u = -1)),
      (u = u >= 0 ? u + 3 : 0),
      (f = r.indexOf(':', u)),
      f >= 0 && (r = r.substr(0, f)),
      (f = r.indexOf('/', u)),
      f >= 0 && (r = r.substr(0, f)),
      (e = i ? r.indexOf('www.') : -1),
      e >= 0 && (r = r.substr(u + 4)),
      r);
}
function addCommonPersistedParams (n) {
  var i = parseQueryParams(),
    t = queryParamsToString(
      i,
      'atlahostname',
      'cdghostname',
      'thhostname',
      'testhooks',
      'adlt',
      'akamaithumb',
      'safesearch',
      'perf',
      'mockimages',
      'mobile',
      'anid',
      'isuserauth',
      'uncrunched',
      'clientid',
      'currentdate',
      'iss'
    ),
    r = n.indexOf('?') === -1 ? '?' : '&';
  return (t = t.length > 0 ? r + t : ''), n + t;
}
var currentQuery = null;
var fab_config = {
  fabStyle: 1,
  fabSbAction: 'FocusSearchBox',
  fabSbActionHover: 'None',
  fabSbActionData: 'None',
  fabTooltip: '',
  micFabAlwaysVisible: false,
  fabClickNoAS: false,
  FabAddSuggestions: false,
  DisableAlsoTryWhenHasPoleRS: false,
};
sj_be(
  _w,
  'click',
  function () {
    _G.UIWP = true;
  },
  1
);

// 設置未登錄用戶的 codexMUIDUser 為 true
const User_UCookieValue = CookieGet('_U')
if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
  _w['_sydConvConfig']['codexMUIDUser'] = true
}

const customChatNum = UserStoreGet('customChatNum')
if (customChatNum != 0) {
  if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
    _w['_sydConvConfig']['maxTurnsPerConversationMuidUser'] = customChatNum
  } else {
    _w['_sydConvConfig']['maxTurnsPerConversation'] = customChatNum
  }
}


if (UserStoreGet('enterpriseEnable')) {
  _w['_sydConvConfig']['disableWelcomeScreen'] = false
  _w['_sydConvConfig']['enableWelcomeScreenV2'] = false
  _w['_sydConvConfig']['enableTelemetryPrivacy'] = true
  _w['_sydConvConfig']['isMSAAuthenticated'] = false
  _w['_sydConvConfig']['isAccountLinkedWithActiveAAD'] = true
  _w['_sydConvConfig']['extraBceOptions'] = 'bcechat'
  _w['_sydConvConfig']['isBingChatForEnterprise'] = true
  _w['_sydConvConfig']['enableMessagePrivacy'] = true
  _w['_sydConvConfig']['PLoadIID'] = 'SERP.5833'
  _w['_sydConvTranslation']['warmWelcomeTitle'] = 'Mr.🆖 AI English Tutor'
  _w['_sydConvTranslation']['welcomeSubtitleText'] = '由Bing AI驅動的人工智能英語學習利器'
  _w['_sydConvTranslation']['inputRaiLabel'] = '你的個人和公司數據在此聊天中受到保護'
}
