/* eslint-disable */
_w['_sydBaseSpecifierPrefix'] = 'rms-answers-SharedStaticAssets-';
_w['_sydPayWallConfig'] = {
  loadSydneyConvResWithPayWall: false,
  useSydneyPayWall: false,
};
_w['_sydConvConfig'] = {
  enableBackgroundFix: true,
  usePill: true,
  enableSydTigerAns: true,
  tigerEnhancedPromptTemplate: 'Search for {0}. Impress me with a great response that helps me complete my most likely intent while showing the smartness, depth, and beauty (bolding, tables, and citations) you can produce. Satisfy my intent as early as possible in the response.',
  // 禁止滑出
  enableScrollOut: false,
  enableSydContext: true,
  sydOptionSets: 'spktxtibmoff,uquopt,enelecintl,gndeleccf,gndlogcf,jbfv203,2tlocretbn,osbsdrecoff',
  sydBalOpts: 'cgptrsndlwcp,flxclmdlspwcp,gldcl1wcp,glfluxv15wcp,invocmax',
  sydCrtOpts: 'invocmax',
  sydPrcOpts: 'invocmax',
  sydBalExtraOpts: 'saharagenconv5',
  sydCrtExtraOpts: 'clgalileo,gencontentv3',
  sydPrcExtraOpts: 'clgalileo,gencontentv3',
  sydIDs: 'gbacf,bggrey,1366cf,multlingcf,stibmoff,tts4,ttsvivn,caccnctacf,specedge,inosanewsmob,wrapnoins,racf,rwt2,dismmaslp,1117gndelecs0,713logprobss0,1111jbfv203,1118wcpdcl,117invocmax,10312tlocret,1025gptv_v2s0,fluxnosearch,1115fluxvs0,727nrprdrt6,727nrprdrt5,codecreator1,cacmuidarb,edgenorrwrap,tstchtadd',
  sydBaseUrl: location.origin,
  compSydRequestSource: 'cib',
  compSydRequestScenario: 'chat',
  augloopEndpoint: 'https://augloop.office.com',
  enableProdEditorEndpoint: true,
  ciqReleaseAudienceGroup: 'Production',
  enableDeterminateProgressBar: true,
  enableSapphireSydVoiceExp: true,
  sapphireArticleContentAPI: 'https://assets.msn.com/content/view/v2/Detail',
  sapphireSydneyQualificationAPI: '/edgesvc/postaj/sydneyqualification',
  sapphireSydneyZeroturnAPI: '/edgesvc/postaj/sydneyzeroturn',
  sapphireSydneyTruncationAPI: '/edgesvc/postaj/sydneytruncationswithcontext',
  enableSydPreloadAudioTTS: true,
  enableSydneyShareLink: true,
  country: 'United States',
  countryConfidence: 8,
  state: 'California',
  city: 'Los Angeles',
  cityConfidence: 0,
  timezoneoffset: '8',
  lat: '78.4156',
  long: '-101.4458',
  language: 'Chinese (China)',
  userMailId: randomString(Math.round(Math.random()*16))+'@'+randomLowercaseString(randomString(Math.round(Math.random()*12)))+'.com',
  username: randomString(Math.round(Math.random()*16)),
  userIpAddress: CookieGet('BingAI_Rand_IP'),
  isMSAAuthenticated: true,
  moveOnlySydXAnswers: true,
  enableSydX1T: true,
  enableSydTestCache: false,
  enableSydCarousel: true,
  traceId: randomLowercaseString(32),
  extraEdgeOptions: 'eredirecturl',
  enableSydMic: true,
  enableSydShare: true,
  enableSydCookLoc: true,
  enableSQMsg: true,
  addDv3Opt: true,
  enableErrorTelemetry: true,
  checkCreatorAnsFor1T: true,
  enableAnsCardSuffix: true,
  isAdultUser: true,
  enableSydCLOC: true,
  enableCdxFeats: true,
  enableShareModalDialog: true,
  enableFdbkFinalized: true,
  enableDM: true,
  enableSydImageCreate: true,
  enableToneCook: true,
toneDefault: 'Creative',
  balTone: 'galileo',
  crtTone: 'h3imaginative',
  prcTone: 'h3precise',
  enableSimpleVoiceInput: true,
  enableSpeechDictationMode: true,
  enableAudioPreloadLimit: true,
  enableSpeechFateTTSStop: true,
  enableSpeechErrorHandling: true,
  enableSpeechTTSLatencyLogging: true,
  enableSpeechIconDarkTheme: true,
  enableSpeechAriaLabel: true,
  enableBalDefault: true,
  enableNewTopicAutoExpand: true,
  enableThreadsAADMSASwitch: true,
  enableMaxTurnsPerConversation: true,
  // 設置已登錄賬號的聊天對話次數
  maxTurnsPerConversation: 30,
  // 設置未登錄賬號的聊天對話次數
  maxTurnsPerConversationMuidUser: 10,
  maxMessageLength: 4000,
  enablePerfTrk: true,
  enableTonePerf: true,
  enableSinglePerfEventPerMessage: true,
  enableAdSlugsMobile: true,
  enableUnauthRedir: true,
  enableVersionedApiCalls: true,
  enableJWTFTRFix: true,
  enableFeedbackClientSideScreenshot: true,
  enableAddMobileTagToCibOnShowConv: true,
  enableStreamSyntheticTextResponses: true,
  enableStreamSyntheticTextResponsesForBalancedTone: true,
  enableStreamSyntheticTextResponsesForCreativeTone: true,
  enableStreamSyntheticTextResponsesForPreciseTone: true,
  syntheticStreamSpeed: 55,
  syntheticStreamSpeedForBalancedTone: 55,
  syntheticStreamSpeedForCreativeTone: 55,
  syntheticStreamSpeedForPreciseTone: 55,
  enableMobileShareAnchorBottom: true,
  enableShareConversation: true,
  enableGetConversationAPIWithSNRProxy: true,
  enableGetSharedMessagesAPIWithSNRProxy: true,
  enableShowShareButtonWithSecurityCheck: true,
  enableServerLogMerging: true,
  enableAutoRecoverFromInvalidSession: true,
  enableAutoRecoverFromInvalidSessionForFirstTurn: true,
  enableCodeCopy: true,
  enableCodeBar: true,
  enableInlineFeedback: true,
  enableInlineFeedbackV21: true,
  enableSerpFeedback: true,
  enablePersistentInputText: true,
  enableActionBarIMEFix: true,
  enableGhostTrailingSpaceByLanguage: true,
  shareLoadingUI: true,
  enableFeedbackInstrumentation: true,
  sydSapphireUpsellVisualSearchQRCodeUrl: 'https://bingapp.microsoft.com/bing?adjust=13uz7blz_13evwnmy',
  enableSydneySapphireUpsellMessageActions: true,
  sydneyContinueOnPhoneShortenQRCodeUrl: 'https://bingapp.microsoft.com/bing?style=newbing\u0026adjust=euhmno2_oy62nz1',
  enableConvModeSwitchAjax: true,
  enableSetToneFromUrl: true,
  convBackBtn: true,
  enableSetConvQueryFlag: true,
  enableSearchQueryForInlineAds: true,
  enableFixForInlineAdsSQ: true,
  codexPartnerScenario: 'SERP',
  enableMessageExport: true,
  enableFlatActionBar: true,
  enablePrivacyConsent: true,
  enableFixCodeXAsBug: true,
  enableThreads: false,
  enableSkipContentOriginCheck: true,
  enableMobileOneClickShareV2: true,
  enableDynamicShareTitle: true,
  enableSharePreview: true,
  enableSharedHoverCitations: true,
  enableScreenshotIgnoreOnCibSerp: true,
  enableStandaloneUtility: true,
  enableThreadShareLandingPage: true,
  enableShareThreadWithNoCache: true,
  enableFixOnReplaceAllJSError: true,
  enableShareCurrentThreadMessagesfromAPI: true,
  enablePreserveTextFormat: true,
  disable2TSearchHistory: true,
  enableSydBeacon: true,
  enableVisualSearch: true,
  visualSearchSubscriptionId: 'Bing.Chat.Multimodal',
  suppressPoleRSWhenEnableSydCarousel: true,
  disablePassBotGreetingInContext: true,
  enableThreadContextMenu: true,
  enableCloudflareCaptcha: true,
  enableResizeObserverWithAnimationFrame: true,
  enableStartPromotion: true,
  enableKnowledgeCardImage: true,
  enableMobileKnowledgeCardOverlay: true,
  suppressPoleRecommendedSearchWhenEnableSydCarousel: true,
  enableCopyButtonInstrumented: true,
  enableMessageExportWithPlainText: true,
  enableMessageExportOnlineWord: true,
  enableMessageExportOnlineExcel: true,
  enableThreadExportOnlineWord: true,
  enableMessageExportV2: true,
  enableDirectlyOpenExportOnlineLink: true,
  enableLoginHintForSSO: true,
  enableLimitToMsaOnlineExport: true,
  enableLimitToAadOnlineExport: true,
  enableMSAuth1stPartyApp: true,
  enableCopyHtml: true,
  enableGetChats: true,
  enableDelayGetChats: true,
  enableExportDocxWithFormat: true,
  enableThreadSync: true,
  enableFlux3P: true,
  disableWelcomeScreen: false,
  enableWelcomeScreenV2: false,
  codexTableVersion: true,
  enableBICHistory: true,
  enableRenderCardRequestIMSearchParams: true,
  typingIndicatorAnimationDuration: 1000,
  enableOnProcessingStartEvent: true,
  enableOnProcessingCompleteEvent: true,
  enableTypewriter: true,
  fileUploadMaxSizeLongContext: 10000000,
  enableUserMessageCopy: true,
  enableDeferredImageCreatorCard: true,
  enableFaviconsV2: true,
  enableUserIpAddress: true,
  enableActionBarV2: true,
  speechSurface: 'desktop',
  enableKatexScroll: true,
  padding2TMobile: 80,
  enablePageHeaderOverlapClamping: true,
  enableThreadShowPlugins: true,
  enableUpdateUserMessageId: true,
  enablePluginPanelFre: true,
  enableMobileFirstClickShare: true,
  personalizationInlineConsentTurn: false,
  enableNoBingSearchResponseBackground: true,
  enableNoSearchPluginMetaMessage: true,
  enableInlineAdsDynamicWidth: true,
  enableShareInThreadsHeader: true,
  enableDeleteSingleConversationMemory: true,
  enableStableAutosuggestion: true,
  threadsAutoSaveOptionset: 'autosave',
  enableUserMessageRewriteAndCopy: true,
  enableBCBSensitivityLabel: true,
  enableOneDs: true,
  enablePromptHandling: true,
  dedicatedIpType: 'unknown',
  enableCIQEmail: true,
  enableCIQAutoScoping: true,
  enableCachedContentFixForIsStartOfSession: true,
  extraNotebookOptionsSets: 'iycapbing,iyxapbing,prjupy',
  notebookMaxMessageLength: 18000,
  initialShowConvPresent: true,
  enableAttributionsV2: true,
  minimumZeroInputSuggestionCount: true,
  imageSearchFormCode: 'IACMIR',
  imageSearchEnableMediaCanvas: true,
  imageSearchMaxImageCount: 5,
  imageSearchForceSquareImages: true,
  enableRelativeSignInUrl: true,
  chatBackgroundColorOverride: 'f7f7f8',
  codexOptionsSetsList: [{
    value: 'iyxapbing'
  },
  {
    value: 'iycapbing'
  }],
  autoHideConvInterval: 3600000,
  enableAjaxBundlePLoad: true,
  PLoadIID: 'SERP.5883'
};
_w['_sydThreads'] = {
  threads: [],
};
_w['_sydConvTranslation'] = {
    actionBarPlaceholder: '輸入問題...（按 [ / ] 鍵打開提示詞）',
  actionBarComposeButton: '新主題',
  actionBarNewChatButtonDesktop: '開始新聊天',
  actionBarNewChatButtonMobile: '新建聊天',
  actionBarOngoingConvPlaceholder: '鍵入消息',
  attachmentLoading: '正在加載附件',
  notiUpdateBrowser: '很抱歉，我們遇到了一些問題。請嘗試刷新頁面並確保你的瀏覽器是最新的',
  bufferMessage1: '我正在使用它，請稍候',
  bufferMessage2: '請稍等',
  bufferMessage3: '花點時間思考...',
  deleteAttachment: '删除附件',
  captchaTitle: '驗証身份',
  captchaDescription: '若要繼續，請在下圖中輸入字符。',
  captchaPlaceholder: '輸入字符...',
  captchaPlaceholderError: '抱歉，請重試。',
  next: '下一步',
  cancel: '取消',
  edit: '編輯',
  feedbackAccessed: '訪問時間',
  feedbackSource: '來源: 與 Mr.🆖 AI English Tutor 的對話，',
  feedbackShareConversationQuery: '什麼是新版必應?',
  feedbackThanksMessageV2: '感謝你的反饋。請重新開始或刷新頁面。',
  messageLearnMore: '深入了解：',
  messageReference: '參考',
  messageReferences: '引用',
  messagePrivacyLabel: 'Mr.🆖 提提你：誠信學習、堅拒抄襲！',
  inputRaiLabel: '',
  letsChat: '我們聊天吧',
  pause: '暫停',
  play: '開始游戲',
  readAloud: '大聲朗讀',
  speechFailedRecognitionError: '抱歉，我無法收聽你的聲音，因為語音服務器已關閉，請稍後再試。',
  speechListening: '我正在聽...',
  speechLoading: '正在等待音頻...',
  speechMediaNotReachableError: '很抱歉，我無法收聽你的聲音，因為你沒有可用的麥克風。',
  speechNoPermissionError: '你需要啟用麥克風，我才能聽到你的聲音。',
  speechAudioPlaybackError: '出錯了。',
  startOver: '重新開始',
  stop: '停止',
  welcomeContainerPrivacyStatement: '隱私',
  welcomeContainerUseTerms: '條款',
  welcomeContainerLearnMore: '了解更多',
  welcomeMessageItemContent1: 'Do a grammar check on the text I provide. Highlight the revised words for me.',
  welcomeMessageItemContent2: 'Give me 5 different versions of the text I provide.',
  welcomeMessageItemContent3: 'Randomly generate a 15-item vocabulary list from Oxford 3000, beginning with different letters, with the order of the entries in the list randomized, in the format "**English word** [繁體中文定義] <word class symbol>: example sentence 例句中文翻譯".',
  welcomeMessageItemTitle1: '🙌 檢查英語語法',
  welcomeMessageItemTitle2: '🎨 獲取改寫建議',
  welcomeMessageItemTitle3: '🧐 生成詞彙列表',
  welcomeMessageItemLabel4: '更多創意中的新增功能：',
  warmWelcomeTitle: 'Mr.🆖 AI English Tutor',
  warmWelcomeTitleLine2: '',
  warmWelcomeAriaLabel: 'Mr.🆖 AI English Tutor',
  welcomeSubtitleText: '由Bing AI驅動的人工智能英語學習利器',
  workToggleDescription: '以及你的結果包括哪些內容',
  feedbackFirstMessage: '非常抱歉沒有幫助到你。是否可以詳細說明你不喜歡的方面?',
  feedbackPromptMessage: '感謝提醒。請提供反饋，以便我們團隊可以查看。',
  feedbackPromptGiveFeedback: '提供反饋',
  feedbackPromptGiveFeedbackAriaLabel: '提供反饋',
  feedbackPromptPositive: '很高興你喜歡這個答案！',
  feedbackFormTitleText: '為什麼這不起作用？',
  feedbackFormInputDefaultText: '在此處添加更多詳細信息。為了幫助保護你的隱私，請不要填入你的姓名或電子郵件地址等個人信息。',
  feedbackFormLegalText: '是否有法律或政策問題？',
  feedbackFormReportAConcern: '報告問題',
  feedbackFormNotificationTitleText: '反饋已提交',
  feedbackFormNotificationBodyText: '感謝你幫助必應改進！',
  feedbackFormThanksMessage: '感謝你提供的反饋!',
  feedbackFormReturnToChatMessage: '返回到聊天',
  serpFeedbackFormTitleText: '請幫助我們改進體驗',
  serpFeedbackFormInputDefaultText: '在此處輸入反饋。為了幫助保護你的隱私，請不要填入你的姓名或電子郵件地址等個人信息。',
  serpFeedbackFormScreenshot: '包括此屏幕截圖',
  serpFeedbackFormRadioLike: '贊',
  serpFeedbackFormRadioDislike: '踩',
  serpFeedbackFormRadioConnectionIssues: '連接問題',
  serpFeedbackFormRadioSlowResponses: '回應緩慢',
  serpFeedbackFormRadioOther: '其他',
  feedbackFormUnderstandDataSharedText: '詳細了解作為診斷數據共享的內容',
  feedbackFormUserConsentText: '將提示共享到 Copilot、從 Copilot 收到的回應，以及此交互的診斷數據?',
  feedbackFormUserConsentYesText: '是',
  feedbackFormUserConsentNoText: '否',
  feedbackFormPrivacyStatement: '隱私聲明',
  feedbackFormPrivacyText: '按“提交”後，你的反饋將用於改進 Microsoft 產品和服務。組織的 IT 管理員將能夠查看和管理反饋數據。',
  compliantPositiveFeedbackFormTitleText: '向 Microsoft 提交反饋',
  compliantPositiveFeedbackQuestionText: '你喜歡哪些方面?',
  compliantPositiveFeedbackDefaultText: '請不要提供任何個人信息。',
  compliantNegativeFeedbackFormTitleText: '向 Microsoft 發送詳細反饋',
  compliantNegativeFeedbackCategoryText: '該內容是',
  compliantNegativeFeedbackQuestionText: '出了什麼問題?',
  compliantFeedbackThanksText: '感謝你提交關於 {0} 的反饋!',
  compliantFeedbackCategoryInaccurate: '不準確',
  compliantFeedbackCategoryOffensive: '冒犯性或不適宜',
  compliantFeedbackCategoryOther: '其他',
  pageTitleText: '配備 GPT-4 的 Mr.🆖 AI English Tutor',
  submit: '提交',
  explore: '瀏覽',
  exploreMore: '瀏覽更多',
  metaInternalSearchQuery: '正在搜尋：`{0}`',
  metaInternalLoaderMessage: '正在為你產生解答...',
  metaInternalImageLoaderMessage: '分析影像: 隱私模糊會隱藏聊天中的人臉',
  metaInternalFileAnalyzeLoaderMessage: 'Analyzing the file {0}',
  metaInternalFileReadLoaderMessage: 'Reading the file {0}',
  compliantMetaInternalLoaderMessage: '從 {0} 產生安全解答',
  messageSharedContent: '共享內容',
  more: '更多',
  morePromptsLink: '查看更多提示',
  expand: '展開',
  welcomeTertiaryTitleText: '使用 AI 的強大功能從 Web 中查找答案、創建書面內容等。',
  actionBarTextInputAriaLabel: '詢問必應',
  seeMore: '查看更多',
  seeLess: '查看更少',
  raiSuggestions: '顯示了解更多建議',
  raiSuggestionsClose: '隱藏了解更多建議',
  actionBarFileUploadButtonAriaLabel: '上傳高達 500 KB 的文字檔案或嘗試 Web URL',
  actionBarFileUploadLongContextButtonAriaLabel: '上傳文字檔案或嘗試 Web URL',
  actionBarFileUploadButtonTooltip: '上傳文字檔案(最多 500 KB)或嘗試 Web URL',
  actionBarFileUploadLongContextButtonTooltip: '上傳文字檔案或嘗試 Web URL',
  actionBarTextInputModeButtonAriaLabel: '使用鍵盤',
  actionBarTextInputUnsupportedFileMessage: '不支援此文件類型。選擇文字文件或圖像文件，然後重試。 ',
  actionBarAddNotebookButtonTooltip: '新主題',
  actionBarAddNotebookButtonAriaLabel: '新主題',
  actionBarSpeechInputModeButtonAriaLabel: '使用麥克風',
  actionBarVisualSearchButtonTooltip: '新增影像',
  actionBarVisualSearchButtonAriaLabel: '新增要搜尋的影像',
  actionBarVisualSearchCoachMarkTitle: '有影像的 Mr.🆖 AI English Tutor',
  actionBarVisualSearchCoachMarkDescription: '現在你可以用影像與 Mr.🆖 AI English Tutor 聊天！ ',
  actionBarVisualSearchCoachMarkImgAlt: '視覺搜尋工具提示影像',
  actionBarVisualSearchCoachMarkText: '使用 AI 分析影像',
  actionBarSubmitButtonAriaLabel: '提交',
  actionBarCancelSpeechInputButtonAriaLabel: '取消語音輸入/讀出',
  actionBarEditModeButtonAriaLabel: '固定',
  actionBarSpeechBtnStartListeningAriaLabel: '使用麥克風',
  actionBarSpeechBtnStopListeningAriaLabel: '停止偵聽',
  actionBarSpeechBtnStopReadoutAriaLabel: '停止讀出',
  attachmentHasSucceded: '已成功新增附件',
  attachmentHasFailed: '附件失敗',
  feedbackLikeButtonAriaLabel: '按讚',
  feedbackDislikeButtonAriaLabel: '不喜歡',
  feedbackOffensiveButtonAriaLabel: '標記為冒犯性',
  feedbackCopyButtonAriaLabel: '複製',
  feedbackRewriteButtonAriaLabel: '重寫',
  feedbackShareButtonAriaLabel: '分享',
  messageReceivedAriaLabelPrefix: '已收到訊息',
  messageReportedOffensiveAndRemoved: '已刪除此訊息，因為它已被舉報待審查。 ',
  messageNotebookPlaceholder: '必應 AI 將在此處創建內容',
  newTopicGreet1: '謝謝你! 知道你什麼時候準備好繼續前進總是很有幫助的。我現在能為你回答什麼問題?',
  newTopicGreet2: '重新開始總是很棒。問我任何問題!',
  newTopicGreet3: '當然，我很樂意重新開始。我現在可以為你提供哪些幫助?',
  newTopicGreet4: '當然，我已準備好進行新的挑戰。我現在可以為你做什麼?',
  newTopicGreet5: '很好，讓我們來更改主題。你在想什麼?',
  newTopicGreet6: '別擔心，我很高興嘗試一些新內容。我現在可以為你回答什麼問題?',
  newTopicGreet7: '好的，我準備好了！感謝重置。我們應該了解哪些內容？ ',
  newTopicGreet8: '感謝刷新！你有新的話題嗎？ ',
  newTopicGreet9: '明白了，讓我們重新開始。接下來該討論什麼？ ',
  newTopicGreet10: '下一步！我可以為你做什麼？ ',
  newTopicGreet11: '好的，我已準備好新主題。我們應該一起了解哪些內容？ ',
  newTopicGreet12: '明白了，請繼續！感謝告訴我。我能提供什麼幫助？ ',
  newTopicSugg1: '教我一個新單字',
  newTopicSugg2: '如何設定可實現的目標?',
  newTopicSugg3: '教我有關登月的資訊',
  newTopicSugg4: '世界上最小的哺乳動物是什麼?',
  newTopicSugg5: '最深的海洋是哪個?',
  newTopicSugg6: '一年有多少小時?',
  newTopicSugg7: '我想學習一項新技能',
  newTopicSugg8: '讓我大笑',
  newTopicSugg9: '有什麼新聞?',
  newTopicSugg10: '給我看鼓舞人心的名言',
  newTopicSugg11: '給我講個笑話',
  newTopicSugg12: '我需要有關家庭作業的幫助',
  newTopicSugg13: '尋找非虛構作品',
  newTopicSugg14: '激勵我!',
  newTopicSugg15: '向我顯示食譜',
  newTopicSugg16: '如何建立預算?',
  newTopicSugg17: '教我一個新單字',
  newTopicSugg18: '天氣如何?',
  newTopicSugg19: '我想學習一項新技能',
  newTopicSugg20: '宇宙是如何開始的?',
  newTopicSugg21: '為什麼人類需要睡眠?',
  newTopicSugg22: '如何制作蛋糕?',
  newTopicSugg23: '火烈鳥為何為粉色?',
  newTopicSugg24: '全息影像的工作原理是什麼?',
  newTopicSugg25: '金字塔是如何建成的?',
  newUserGreet: '很高興認識你！我是必應，我不僅僅是一個搜尋引擎。我可以幫助你規劃群、寫一個朋友或問宇宙。你想要探索什麼？ ',
  newUserSugg1: '寫詩',
  newUserSugg2: '玩小遊戲',
  newUserSugg3: '給我一個笑話',
  repeatUserGreet: '又見面了。我很樂意為你提供任何幫助。如何為你效勞，改進你的一天?',
  repeatUserSugg1: '生成故事',
  repeatUserSugg2: '告訴我一個事實',
  repeatUserSugg3: '你可以做什麼?',
  creativeGreet: '好吧!這就是創意。我能幫什麼忙？ ',
  balancedGreet: '好的，我們來找答案並聊會天。我可以為你做什麼？ ',
  preciseGreet: '感謝聊天。今天我能幫你嗎？ ',
  creativeSugg1: '告訴我的星座',
  creativeSugg2: '讓我們寫一首節拍詩',
  creativeSugg3: '給我一個你想問的問題',
  balancedSugg1: '給我個週末度假的主意',
  balancedSugg2: '附近哪裡可以看到星星？ ',
  balancedSugg3: '哪種花最香？ ',
  preciseSugg1: '我需要幫忙做研究',
  preciseSugg2: '給我列出今晚晚餐的購物清單',
  preciseSugg3: '誰發明語言？ ',
  close: '關閉',
  newTopicPrompt: '通過新主題，可以開始與 Mr.🆖 AI English Tutor 就任何主題進行全新對話',
  typingIndicatorStopRespondingAriaLabel: '停止回應',
  loading: '正在載入',
  canceling: '正在取消',
  welcomeLearnMessage: 'Mr.🆖 AI English Tutor 由 AI 提供支持，因此可能會出現意外和錯誤。請分享回饋，以便我們可以改進!',
  welcomeLearnMessage2: 'Mr.🆖 AI English Tutor 會處理你輸入的字詞，以產生 AI 驅動的回應，並改善你的體驗。 ',
  welcomeLearnFeedbackSubstitute: '分享回饋',
  adsDisclaimer: '廣告不是基於工作區識別或聊天歷史記錄的目標。 {0}。 ',
  adsDisclaimerLearnMoreLink: '了解更多',
  actionBarNewlineTooltip: '使用 Shift+Enter 為較長的訊息建立換行符',
  notiChatEnd: '聊天主題已結束。 ',
  notiRestartChat: '在 {0} 小時內開始新主題',
  notificationAttemptingToReconnect: '正在嘗試重新連接...',
  notificationProcessing: '正在嘗試連接，請稍候',
  notificationLostConnection: '很抱歉，你的連線似乎已斷開。 ',
  notificationLostConnectionCta: '是否要嘗試重新連線？ ',
  sydneySapphireConsentDenyText: '拒絕',
  typingIndicatorStopStreamingAriaLabel: '停止串流',
  sydneyCarouselCollapse: '折疊',
  sydneyCarouselTitle: '最近的聊天主題',
  messageActionsCopy: '複製',
  messageActionsCopying: '正在複製',
  messageActionsCopied: '已複製',
  messageActionsCopyError: '錯誤',
  messageActionsReport: '報告',
  tooltipPositive: '按讚',
  tooltipNegative: '不喜歡',
  tooltipShare: '共享',
  tooltipMore: '更多',
  tooltipSendToPhone: '在手機上繼續',
  codeDisclaimer: 'AI 產生的程式碼。仔細查看和使用。 {0}.',
  codeDisclaimerLinkLabel: '有關常見問題解答的詳細資訊',
  exportTitle: '導出',
  exportTextTitle: '下載為文字(.txt)',
  exportPdfTitle: '以 PDF (.pdf)格式下載',
  exportWordTitle: '下載為文檔(.docx)',
  exportWordOnlineTitle: '在 Word 中編輯',
  exportExcelTitle: '下載為工作簿(.xlsx)',
  exportExcelOnlineTitle: '在 Excel 中編輯',
  exportTableTitle: '表格',
  exportToastViewButtonLabel: '查看',
  exportSuccessToastTitle: '已匯出檔案。某些格式和圖像可能無法匯出。 ',
  exportErrorToastTitle: '導出失敗',
  exportLoadingToastTitle: '正在匯出...',
  exportedFileUserTitle: '使用者',
  exportedFileBotTitle: 'Mr.🆖 AI English Tutor',
  exportedFileSourceTitle: '來源',
  mobileUpsellMessage1: '掃描此 QR 碼以在移動必應應用上繼續此對話',
  mobileUpsellTitle1: '在手機上繼續',
  visualSearchMobileUpsellLabel: '在手機上使用必應應用程式',
  mobileUpsellTitle2: '使用必應應用程式拍攝照片',
  mobileUpsellMessage2: '掃描 QR 碼以在行動裝置上使用必應應用程式拍攝此照片',
  actionBarAutoSuggestTab: 'Tab',
  actionBarAutoSuggestTap: '點選',
  actionBarKeyboardHint: '輸入',
  feedbackShareAnswer: '查看此必應答案',
  feedbackShareGenerated: '查看我使用必應產生的內容',
  feedbackShowTonesButtonAriaLabel: '顯示所有音調',
  feedbackHideTonesButtonAriaLabel: '隱藏所有色調',
  feedbackHidePreciseToneButtonAriaLabel: '隱藏精確',
  feedbackShareErrorToast: '共用失敗。 ',
  serpfeedback: '回饋',
  shareConversation: '分享整個對話',
  speechAuthenticationError: '身份驗證失敗。請稍後重試。 ',
  speechOnlineNotification: '語音輸入由 Microsoft 線上服務處理，不會進行收集或儲存。 ',
  speechUnknownError: '出錯了。 ',
  refresh: '刷新',
  feedbackShareContent: '以下是我使用新的必應（全球首個 AI支援的應答引擎）產生的答案。點擊可查看完整答案，然後請你也來試試看。 ',
  fileUploadDragAndDropLabel: '在此處刪除映像或檔案',
  fileUploadUnsupportedFileMessage: '此檔案類型不支援。選擇文字文件，然後重試。 ',
  fileUploadMaxSizeLimitErrorMessage: '檔案大小已逾限。只能上傳高達 500KB 的檔案。 ',
  fileUploadMaxSizeLimitLongContextErrorMessage: '檔案大小已逾限。只能上傳大小不超過 10MB 的檔案。 ',
  fileUploadMaxSizeLongContextErrorMessage: 'File size exceeded. You can only upload a file up to {0}MB.',
  fileUploadTextFileUploadErrorMessage: '無法上傳檔案。 ',
  fileUploadWebPageInfoUploadErrorMessage: '無法從網頁擷取內容。 ',
  fileUploadFlyoutInputboxAriaLabel: '貼上網頁 URL',
  fileUploadFlyoutTitle: '新增文字檔',
  fileUploadFlyoutUploadButtonLabel: '從此裝置上傳',
  fileUploadGenericErrorMessage: '無法上傳該檔案。請重試',
  preview: '預覽',
  toneSelectorDescription: '選擇對話樣式',
  toneSelectorMoreCreative: '更\\r\\n有創意',
  toneSelectorMoreBalanced: '更\\r\\n平衡',
  toneSelectorMorePrecise: '更\\r\\n精確',
  toneSelectorFaster: '更快',
  toneSelectorWithGPT4: '使用 GPT-4',
  notificationClientIdChangedInNotebook: '你的筆記本已過期。 ',
  notificationClientIdChangedInNotebookCta: '開始新主題',
  notificationMaxTurnsPerDay: '很抱歉，你已達到可在 24 小時內發送到必應的郵件限制。請稍後回來查看!',
  notificationMaxTurnsPerConversation: '很抱歉，此對話已達到其限制。使用“掃除”按鈕清除此內容並進行更多聊天。 ',
  notificationMaxTurnsPerConversationInNotebook: '很抱歉，我想我們需要繼續操作!使用左側的“新主題”按鈕清除內容並重新開始。 ',
  notificationMaxTurnsForMuidUsers: '你已達到今天的對話限制。 ',
  notificationMaxTurnsForInPrivateUsers: '你已達到 inPrivate 模式的會話限制。打開非 inPrivate 視窗以繼續聊天',
  notificationUnauthorizedMuidUsersCta: '登入以繼續你的聊天。 ',
  muidUserHeaderText: '',
  muidUsersTermsCond1: '通過單擊“開始使用”，並繼續與 Mr.🆖 AI English Tutor 交互，即表示你接受',
  muidUsersTermsCond1Inline: '通過繼續與 Mr.🆖 AI English Tutor 交互，你將接受 ',
  muidUsersTermsCond2: '並確認你已查看',
  muidUsersPrivacyStatement: '隱私權聲明',
  muidUsersTermsOfUse: '使用條款',
  muidUserGetStartedText: '開始使用',
  muidUserContinueText: '繼續',
  welcomeMobSugg1: 'Mr.🆖 AI English Tutor 如何使用 AI?',
  welcomeMobSugg2: 'Mr.🆖 AI English Tutor 還可以做什麼？',
  welcomeMobSugg3: '科技領域的最新消息是什麼？ ',
  of: '共',
  notificationResetConversation: '很抱歉，似乎出現錯誤。 ',
  notificationResetConversationCta: '讓我們重新開始吧。 ',
  toneSelectorCreativeTooltip: '清除對話並開始原創和富有想像力的聊天',
  toneSelectorBalancedTooltip: '清除對話並開始一個資訊豐富且友好的聊天',
  toneSelectorPreciseTooltip: '清除對話並開始簡潔直截了當的聊天',
  toneSelectorSuppressedTooltip: '暫時無法使用。請稍後再試!',
  notificationDisengaged: '也許該換個新話題了。 ',
  notificationForbidden: '很抱歉，你似乎不再有權利存取此功能。請幾天後再檢查一次。 ',
  notificationTooManyRequests: '很抱歉，現在需求量非常大。請稍後重試。 ',
  notificationUnauthorized: '很抱歉，你似乎已註銷。 ',
  notificationUnauthorizedCta: '請重新登入。 ',
  notificationUnauthorizedMissingDOB: '可能需要確認你的出生日期才能繼續聊天。 ',
  notificationUnauthorizedMissingDOBCta: '在此更新你的帳號。 ',
  notificationUnauthorizedChildUser: '很抱歉，必應聊天不適用於此帳戶。 ',
  notificationUnauthorizedChildUserCta: '在 bing.com 上瀏覽 Web!',
  notificationMessageError: '上一則訊息似乎已中斷。 ',
  notificationMessageErrorInNotebook: '你上次的提示似乎已中斷。 ',
  notificationSharedTip: '此對話\u003cstrong\u003e「{0}」\u003c/strong\u003e已於 {1} 與你分享',
  notificationNetworkOffline: '抱歉，你尚未連線。請檢查你的網路連線並重試。 ',
  notificationAutoRefreshConversation: '出錯了。正在解決，請稍候。 ',
  notificationAutoResendOnConnectionError: '你的連線暫時遺失。正在重新連接，請稍候。 ',
  notificationAutoRecoverOnMessageError: '很抱歉，你最後一封郵件似乎已中斷。正在解決，請稍候。 ',
  notificationAutoRecoverOnMessageErrorInNotebook: '很抱歉，你最後一封郵件似乎已中斷。正在解決，請稍候。 ',
  notificationContinueRecovering: '我仍在解決問題，請稍候。 ',
  signInCta: '登入 ',
  signInDescription: ' 以提出更多問題並進行更長的對話',
  signInDescriptionInPrivate: '打開非 inPrivate 窗口，以便進行更長的對話或提出更多問題',
  copyCodeButtonTooltip: '複製',
  threadsSharedOnDate: '於 {0} 分享',
  threadsMore: '更多',
  threadsExportPanelTitle: '選擇格式',
  threadsExportPanelAriaLabel: '選擇',
  threadsAADMSARedirectConfirm: '切換使用者設定',
  threadsAADMSARedirectDescription: '正在使用 Microsoft 帳戶保存你的對話歷史記錄。下次使用個人帳戶登入時，它將在此處顯示。 ',
  privateThreadConvDefaultTitle: '未儲存的對話',
  threadsCancel: '取消',
  threadsChatHistory: '聊天記錄',
  threadsConfirm: '確認',
  threadsDaysAgo: '{0} 天前',
  threadsDefaultChatName: '無標題的聊天',
  threadsDelete: '刪除',
  threadsDescription: 'AI 支持的助手現可自動保存聊天。你可以從任何設備、桌面或移動設備訪問聊天，無縫地繼續。',
  threadsDescriptionNote: '請注意，除非專門保存，否則所有聊天將在 90 天內自動刪除。',
  threadsEdit: '重命名',
  threadsLoad: '加載聊天',
  threadsMinimizeRecent: '最小化最近的聊天',
  threadsMinimizeSaved: '最小化保存的聊天',
  threadsPreview: '預覽',
  threadsPreviewText: '跳回最近聊天',
  threadsRecentTitle: '最近的活動',
  threadsRecentTitleShort: '最近使用',
  threadsSavedTitle: '已保存',
  threadsSeeAllRecent: '查看所有最近的聊天',
  threadsSeeAllSaved: '查看所有保存的聊天',
  threadsTitle: '聊天',
  threadsTitleForFlux: '菜單',
  threadsYesterday: '昨天',
  threads2TLastAccessed: '上次應答時間',
  threads2TInfoChanged: '此信息可能已更改，因為',
  threads2TArchivedText: '屏幕截圖',
  threads2TReloadDescription: '單擊“重新加載”以顯示來自 Web 的最新信息',
  threads2TFailedSearch: '請參閱最新 Bing.com',
  threads2TReload: '搜索 Bing.com',
  injectedActionCardTitle: '就此頁面進行聊天?',
  injectedActionCardConfirm: '發送',
  injectedActionCardDeny: '忽略',
  webPageContextPrefix: '已訪問網站',
  useGPT4SwitchLabel: '使用 GPT-4',
  zeroInputSuggestionFallback1: 'Randomly generate a 15-item vocabulary list from Oxford 3000, beginning with different letters, with the order of the entries in the list randomized, in the format "**English word** [繁體中文定義] <word class symbol>: example sentence 例句中文翻譯".',
  zeroInputSuggestionFallback2: '對於一個預算有限的六口之家來說，會首選哪三款車型？',
  zeroInputSuggestionFallback3: '寫一個我的同事會覺得有趣的笑話',
  zeroInputSuggestionFallback4: 'Do a grammar check on the text I provide. Highlight the revised words for me.',
  zeroInputSuggestionFallback5: '撰寫關於魚和青蛙尋找愛的原創寓言故事',
  zeroInputSuggestionFallback6: 'Give me 5 different versions of the text I provide.',
  zeroInputSuggestionFallback7: '為具有諷刺風格的新社交媒體平台創建一個口號',
  zeroInputSuggestionCategory1: '生成詞彙列表',
  zeroInputSuggestionCategory2: '比較',
  zeroInputSuggestionCategory3: '大笑',
  zeroInputSuggestionCategory4: '檢查英語語法',
  zeroInputSuggestionCategory5: '寫入',
  zeroInputSuggestionCategory6: '獲取改寫建議',
  zeroInputSuggestionCategory7: '創建',
  zeroInputDescription: 'Mr.🆖 AI English Tutor 是由Bing AI驅動的人工智能英語學習利器',
  discoverMessageItemTitle: '📝 一起重寫文字',
  discoverMessageItemContent: '嘗試從頁面中選擇文字以查看我們可以一起執行的操作',
  pluginTitle: '插件',
  bookNowWithOpenTable: '立即使用 OpenTable 預約',
  scrollLeft: '向左滾動',
  scrollRight: '向右滾動',
  responses: '回應',
  personalizationConsentTitleText: '已為你設定個人化對話',
  personalizationConsentTitleTextEu: '已為你設定個人化對話',
  personalizationConsentContentText1: '必應使用聊天歷史記錄中的 Insights 使對話成為獨一無二的對話。 ',
  personalizationConsentContentText1Eu: '共享聊天歷史記錄時，根據你和你的興趣自訂回應。 ',
  personalizationConsentContentText2: '。 ',
  personalizationConsentLearnMoreText: '在我們的常見問題中了解詳細資訊',
  personalizationConsentLearnMoreTextEu: '了解有關個人化的詳細資訊',
  personalizationConsentContentSettingsText: '隨時在設定中關閉個人化設定。 ',
  personalizationConsentStatusPositiveText: '已啟用個人化。 ',
  personalizationConsentStatusNegativeText: '未啟用個人化。 ',
  personalizationConsentSettingsText1: '若要修改，請造訪',
  personalizationConsentSettingsLinkText: '聊天設定',
  personalizationConsentSettingsText2: '頁面',
  personalizationConsentTurnOnText: '開啟',
  personalizationConsentTurnOffText: '不打開',
  pluginEnabledPlugin: '已啟用',
  pluginEnabledNumber: '{0} / {1}',
  pluginStartNewTopic: '開始新主題',
  pluginToChangePlugin: '更改插件',
  pluginNotificationMaxExceeded: '已啟用的最大插件數',
  pluginNotificationMaxExceededV2: '已啟用最大數量的插件。 ',
  pluginNotificationExclusive: '{0} 與 {1} 太相似。請選擇一個',
  pluginNotificationExclusiveV2: '{0} 和 {1} 可以起到類似的作用。請選擇一個。 ',
  pluginTerms: '使用條款',
  pluginPrivacy: '隱私權策略',
  pluginPanelFreTitle: '插件現在可用',
  pluginPanelFreTextLabel: '新建:',
  pluginPanelFreText: '打開插件，幫助你從喜歡的品牌中查找餐廳預訂、航班等。',
  pluginPanelFreDismiss: '忽略',
  pluginPanelAlertTitle: '插件在“平衡”模式下不可用',
  pluginPanelAlertCta: '重置對話 ',
  pluginPanelAlertSubtitle: '並使用「更多創意」或「更精確」對話樣式，然後重試。 ',
  pluginLimitationDataShared: '將與你選擇的插件共用資料。 ',
  pluginLimitationTitle: '將插件與 AI 配合使用',
  pluginLimitationMax: '最多為任一個對話線程選擇 3 個插件。 ',
  pluginLimitationMaxV2: '為對話最多選擇 {0} 個插件。 ',
  pluginLimitationLock: '在選擇「新主題」進行更改之前，插件會鎖定在對話中。 ',
  pluginLimitationLockV2: '若要在開始對話後更改插件，請選擇 {0}。 ',
  pluginPanelNolimit: '停用 {0} 不會影響插件限制',
  activatetoUsePlugins: '啟動 {0} 以使用插件',
  threadsT​​oggleExpansion: '切換擴充',
  threadsEnabledPlugins: '已啟用插件:',
  bingSearchDisabled: '搜尋**已停用**。 ',
  bingSearchDisabledforMessage: '搜尋已停用',
  activateSearch: '啟動新主題並啟動搜尋',
  visualSearchFlyoutTitle: '新增圖片',
  visualSearchGenericErrorMessage: '無法上傳該檔案。請重試。 ',
  visualSearchUnsupportedFileMessage: '不支援此檔案類型。選擇圖像文件，然後重試。 ',
  visualSearchInvalidUrlMessage: '抱歉 - 你提供的 URL 似乎無效。請重試',
  visualSearchFlyoutInputboxAriaLabel: '貼上圖片或連結',
  visualSearchFlyoutTakePhotoButtonLabel: '拍照',
  visualSearchDragAndDropLabel: '將圖片拖曳到這裡',
  visualSearchFlyoutUploadButtonLabel: '從此裝置上傳',
  raiDisclaimerLabel: 'AI 產生的內容可能不正確',
  slimHeaderTitle: '查看 AI 支持的解答',
  starterPageTitle: '由Bing AI驅動的人工智能英語學習利器',
  starterDescription: '用你自己的語言與我聊天。如果感到卡住，請選擇以下開場白之一，以觀察我是如何運作的：',
  starterSubtitle1: '進行對話',
  starterSubtitle2: '釋放你的創造力',
  starterSubtitle3: '更智能地搜索',
  starterContent1: '像日常聊天一樣使用自然語句並詢問后續內容時，效果最佳',
  starterContent2: '無論是用圖像還是文字，我可以通過讓你的願景變為現實來激發你的創造力',
  starterContent3: '與我聊天是一種新搜索方式。讓我匯總 Web 內容並提供答案',
  starterChatQuery1: '你認為其他行星上有生命嗎？地球的獨特之處是什麼？',
  starterChatQuery2: '如果我睡眠遇到問題，但隻在夏天發生，是怎麼回事？',
  starterChatQuery3: '我想開辟一個花園，但我對此一無所知。第一步需要做什麼？',
  starterChatQuery4: '你認為鱷魚或灰熊會在搏斗中獲勝嗎？',
  starterChatQuery5: '我最近讀了很多非虛構類書籍。你能幫我找到我喜歡的主題的虛構類版本嗎？',
  starterChatQuery6: '讓我們進行一次對話，其中你說的所有內容都是用表情符號編寫的。',
  starterChatQuery7: '我一直在考慮搬到一個新的地方。你認為我應該去哪兒？',
  starterChatQuery8: '我曾經寫過日記，但最近經常偷懶。我如何才能保持習慣？',
  starterChatQuery9: '你是否會像人類一樣做夢？你會夢到什麼？',
  starterChatQuery10: '是否可能同時發生地震、海嘯和火山噴發？',
  starterCreateQuery1: '我有一隻黑毛的小狗，除了肚子上的毛是白色的。請將它畫成卡通形象。',
  starterCreateQuery2: '為我的 3 歲的侄女寫一個睡前故事。她喜歡馬和魔法，而且我認為這個故事應該押韻”',
  starterCreateQuery3: '用一位高傲自大的教授的語氣撰寫一篇短文，來証明月亮比太陽更好',
  starterCreateQuery4: '用印象派風格畫一隻在冰山上晒太陽的北極熊。它還應該在喝檸檬水',
  starterCreateQuery5: '讓我們來創造一種顏色，並撰寫一個社交媒體帖子向全世界介紹它',
  starterCreateQuery6: '作為由 Christian Bale 扮演的蝙蝠俠，請告訴我如何騎著摩托車應對交通',
  starterCreateQuery7: '用一位在家釀酒並引發小型爆炸的爸爸的語氣，為一個新的啤酒品牌制作銷售宣傳',
  starterCreateQuery8: '為一家咖啡館設計一副海報，其中包含日落並充分利用空間',
  starterCreateQuery9: '畫一隻身為湖上躉船船長的長頸鹿',
  starterCreateQuery10: '為一篇有關女權主義文學歷史的論文撰寫簡介段落，並為我提供五個寫作提示以繼續',
  starterCompareQuery1: '為我找一份提拉米蘇的菜譜，為我制作一個購物清單，然后進行排列，以便我可以在商店中快速找到配料',
  starterCompareQuery2: '為我提供的今天的本地新聞匯報，不包括體育內容”',
  starterCompareQuery3: '用五個要點總結最新的 AI 研究，並得出接下來的發展趨勢的結論',
  starterCompareQuery4: '創建一個表格，用來按品牌、價格、安全功能和可能的附加設備比較最佳電動車',
  starterCompareQuery5: '這附近有兒童游樂場的最近的公園在哪裡？',
  starterCompareQuery6: '為我晚上要做的意大利菜提供三種葡萄酒建議。這道菜以西紅柿為主料，並且有點辣。',
  starterCompareQuery7: '為我提供 UN 的最新焦點的概要',
  starterCompareQuery8: '創建一個表格，用來比較出人意料的普利策獎獲得者及其原因',
  starterCompareQuery9: '用孩子能夠理解的方式介紹 Internet 的運作原理',
  starterCompareQuery10: '將“詩歌簡介”這首詩翻譯為法語，並用英語簡要解釋任何損失的含義',
  notificationMaxTurnsAndOpenEdge: '你已達到對話限制。若要繼續聊天，',
  notificationMaxTurnsAndOpenEdgeCta: '在 Microsoft Edge 中打開',
  actionBarPromptGuideToolTip: '提示指南',
  actionBarAttachButtonToolTip: '附加',
  promptLibraryButtonLabel: '查看提示',
  actionBarLongPlaceholder: '詢問我任何內容或鍵入/新增人員、檔案等',
  actionBarNotebookPlaceholder: '你有什麼想法? 寫與 AI 協作的詳細提示。使用 Shift+Enter 提交郵件。 ',
  thirdPartyBingChatAttribution: '由 AI 提供的結果',
  thirdPartyRAIDisclaimer: '可能會出現意外和錯誤',
  thirdPartyPrivacyHyperlink: '隱私',
  thirdPartyTermsHyperlink: '條款',
  usePreciseLocation: '更新地點',
  basedOnLocation: '基於: {0}、{1}',
  basedOnYourLocation: '基於你的位置',
  locationFetchErrorMessage: '權限被拒絕',
  locationLearnMore: '(了解詳細資料)'
};
function parseQueryParamsFromQuery (n, t) {
  var u, f, e, o;
  t === void 0 && (t = !0);
  var r = [],
    s = n && n.length > 0 ? n.split('&') : [],
    h = s.length,
    i = null;
  for (u = 0; u < h; u++)
    (f = s[u]), (e = f.indexOf('=')), e > 0 && ((i = f.substr(0, e)), i.charAt(0) == '?' && (i = i.substr(1)), i && ((i = i.toLowerCase()), (r[i] = f.substr(e + 1))));
  return t && ((o = r.first), (r.first = null == o || o == '0' ? 1 : parseInt(o))), r;
}
function parseQueryParams () {
  var n = '';
  return (
    (n = typeof Bing != 'undefined' && Bing.Url && Bing.Location ? Bing.Url.getQueryString(Bing.Location.get()) : _w.location.search.substring(1)), parseQueryParamsFromQuery(n)
  );
}
function convertQueryParamsToUrlStr (n, t) {
  t === void 0 && (t = null);
  var i = t ? t : _w.location.pathname.replace(/^\/+/, '/');
  return i + '?' + queryParamsToString(n);
}
function queryParamsToString (n) {
  for (var e, o, r, u, s, f, t = [], i = 1; i < arguments.length; i++) t[i - 1] = arguments[i];
  if (((e = []), (u = t.length), u == 0)) for (s in n) n.hasOwnProperty(s) && (t.push(s), u++);
  for (f = 0; f < u; f++) (o = t[f]), (r = n[o]), (r || r === 0) && e.push(o + '=' + r);
  return e.join('&');
}
function getCurrentQuery () {
  if (!currentQuery) {
    var n = parseQueryParams();
    currentQuery = n.q;
  }
  return currentQuery;
}
function extractDomainFromUrl (n, t, i) {
  var r, u, f, e;
  return typeof n != 'string'
    ? null
    : ((r = n),
      (u = r.indexOf('://')),
      u >= 0 && !t && ((r = r.substr(u + 3)), (u = -1)),
      (u = u >= 0 ? u + 3 : 0),
      (f = r.indexOf(':', u)),
      f >= 0 && (r = r.substr(0, f)),
      (f = r.indexOf('/', u)),
      f >= 0 && (r = r.substr(0, f)),
      (e = i ? r.indexOf('www.') : -1),
      e >= 0 && (r = r.substr(u + 4)),
      r);
}
function addCommonPersistedParams (n) {
  var i = parseQueryParams(),
    t = queryParamsToString(
      i,
      'atlahostname',
      'cdghostname',
      'thhostname',
      'testhooks',
      'adlt',
      'akamaithumb',
      'safesearch',
      'perf',
      'mockimages',
      'mobile',
      'anid',
      'isuserauth',
      'uncrunched',
      'clientid',
      'currentdate',
      'iss'
    ),
    r = n.indexOf('?') === -1 ? '?' : '&';
  return (t = t.length > 0 ? r + t : ''), n + t;
}
var currentQuery = null;
var fab_config = {
  fabStyle: 1,
  fabSbAction: 'FocusSearchBox',
  fabSbActionHover: 'None',
  fabSbActionData: 'None',
  fabTooltip: '',
  micFabAlwaysVisible: false,
  fabClickNoAS: false,
  FabAddSuggestions: false,
  DisableAlsoTryWhenHasPoleRS: false,
};
sj_be(
  _w,
  'click',
  function () {
    _G.UIWP = true;
  },
  1
);

// 設置未登錄用戶的 codexMUIDUser 為 true
const User_UCookieValue = CookieGet('_U')
if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
  _w['_sydConvConfig']['codexMUIDUser'] = true
}

const customChatNum = UserStoreGet('customChatNum')
if (customChatNum != 0) {
  if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
    _w['_sydConvConfig']['maxTurnsPerConversationMuidUser'] = customChatNum
  } else {
    _w['_sydConvConfig']['maxTurnsPerConversation'] = customChatNum
  }
}


if (UserStoreGet('enterpriseEnable')) {
  _w['_sydConvConfig']['disableWelcomeScreen'] = false
  _w['_sydConvConfig']['enableWelcomeScreenV2'] = false
  _w['_sydConvConfig']['enableTelemetryPrivacy'] = true
  _w['_sydConvConfig']['isMSAAuthenticated'] = false
  _w['_sydConvConfig']['isAccountLinkedWithActiveAAD'] = true
  _w['_sydConvConfig']['extraBceOptions'] = 'bcechat'
  _w['_sydConvConfig']['isBingChatForEnterprise'] = true
  _w['_sydConvConfig']['enableMessagePrivacy'] = true
  _w['_sydConvConfig']['PLoadIID'] = 'SERP.5833'
  _w['_sydConvTranslation']['warmWelcomeTitle'] = 'Mr.🆖 AI English Tutor'
  _w['_sydConvTranslation']['welcomeSubtitleText'] = '由Bing AI驅動的人工智能英語學習利器'
  _w['_sydConvTranslation']['inputRaiLabel'] = 'Mr.🆖 提提你：誠信學習、堅拒抄襲！'
}
